* Path, Component, Release: cmhv7sf/rel/HSPICE/models/fixed_corner_hv.inc, 7hv_models, mod_cmhv7sf
* CMVC Revision: 3.0
*
* *********************************************************************
*
*>  High Voltage Device Fixed Process Corner Parameter Settings
*
*   High Voltage Device corner parameter settings only.
*
*
* *********************************************************************

.lib tt_nfeti20t
.param
+ dbeta1_nfeti20t_fc =   0.0000e+00
+ dcj_nfeti20t_fc =   0.0000e+00
+ dcgso_nfeti20t_fc =   0.0000e+00
+ dk1_nfeti20t_fc =   0.0000e+00
+ dvth1_nfeti20t_fc =   0.0000e+00
+ dvsat_nfeti20t_fc =   0.0000e+00
+ dcgdx1_nfeti20t_fc =   0.0000e+00
+ dvth0_nfeti20t_fc =   0.0000e+00
+ dtox_nfeti20t_fc =   0.0000e+00
+ dbeta2_nfeti20t_fc =   0.0000e+00
+ dvth2_nfeti20t_fc =   0.0000e+00
+ dxw_nfeti20t_fc =   0.0000e+00
+ ddvt0_nfeti20t_fc =   0.0000e+00
+ drj_nfeti20t_fc =   0.0000e+00
+ ddlc_nfeti20t_fc =   0.0000e+00
+ dk2_nfeti20t_fc =   0.0000e+00
+ dxl_nfeti20t_fc =   0.0000e+00
+ duo_nfeti20t_fc =   0.0000e+00
.endl tt_nfeti20t

.lib ff_nfeti20t
.param
+ dbeta1_nfeti20t_fc =   1.6360e+00
+ dcj_nfeti20t_fc =   0.0000e+00
+ dcgso_nfeti20t_fc =   0.0000e+00
+ dk1_nfeti20t_fc =   0.0000e+00
+ dvth1_nfeti20t_fc =  -3.7642e-01
+ dvsat_nfeti20t_fc =   0.0000e+00
+ dcgdx1_nfeti20t_fc =   0.0000e+00
+ dvth0_nfeti20t_fc =  -3.2962e-02
+ dtox_nfeti20t_fc =  -1.5000e-10
+ dbeta2_nfeti20t_fc =   4.6904e-01
+ dvth2_nfeti20t_fc =  -8.6833e-03
+ dxw_nfeti20t_fc =   0.0000e+00
+ ddvt0_nfeti20t_fc =   3.6781e+00
+ drj_nfeti20t_fc =  -1.3500e-03
+ ddlc_nfeti20t_fc =   0.0000e+00
+ dk2_nfeti20t_fc =   0.0000e+00
+ dxl_nfeti20t_fc =   0.0000e+00
+ duo_nfeti20t_fc =   7.8832e+00
.endl ff_nfeti20t

.lib ss_nfeti20t
.param
+ dbeta1_nfeti20t_fc =  -1.6360e+00
+ dcj_nfeti20t_fc =   0.0000e+00
+ dcgso_nfeti20t_fc =   0.0000e+00
+ dk1_nfeti20t_fc =   0.0000e+00
+ dvth1_nfeti20t_fc =   2.7102e-01
+ dvsat_nfeti20t_fc =   0.0000e+00
+ dcgdx1_nfeti20t_fc =   0.0000e+00
+ dvth0_nfeti20t_fc =   3.0453e-02
+ dtox_nfeti20t_fc =   1.5000e-10
+ dbeta2_nfeti20t_fc =  -4.6920e-01
+ dvth2_nfeti20t_fc =   2.5538e-01
+ dxw_nfeti20t_fc =   0.0000e+00
+ ddvt0_nfeti20t_fc =  -4.0940e+00
+ drj_nfeti20t_fc =   1.6254e-03
+ ddlc_nfeti20t_fc =   0.0000e+00
+ dk2_nfeti20t_fc =   0.0000e+00
+ dxl_nfeti20t_fc =   0.0000e+00
+ duo_nfeti20t_fc =  -1.1559e+01
.endl ss_nfeti20t

.lib fs_nfeti20t
.param
+ dbeta1_nfeti20t_fc =   1.3477e+00
+ dcj_nfeti20t_fc =   0.0000e+00
+ dcgso_nfeti20t_fc =   0.0000e+00
+ dk1_nfeti20t_fc =   0.0000e+00
+ dvth1_nfeti20t_fc =  -3.5969e-01
+ dvsat_nfeti20t_fc =   0.0000e+00
+ dcgdx1_nfeti20t_fc =   0.0000e+00
+ dvth0_nfeti20t_fc =  -2.7544e-02
+ dtox_nfeti20t_fc =   0.0000e+00
+ dbeta2_nfeti20t_fc =   3.2209e-01
+ dvth2_nfeti20t_fc =  -1.9313e-01
+ dxw_nfeti20t_fc =   0.0000e+00
+ ddvt0_nfeti20t_fc =   0.0000e+00
+ drj_nfeti20t_fc =  -3.1438e-02
+ ddlc_nfeti20t_fc =   0.0000e+00
+ dk2_nfeti20t_fc =   0.0000e+00
+ dxl_nfeti20t_fc =   0.0000e+00
+ duo_nfeti20t_fc =   9.5123e+00
.endl fs_nfeti20t

.lib sf_nfeti20t
.param
+ dbeta1_nfeti20t_fc =  -1.3511e+00
+ dcj_nfeti20t_fc =   0.0000e+00
+ dcgso_nfeti20t_fc =   0.0000e+00
+ dk1_nfeti20t_fc =   0.0000e+00
+ dvth1_nfeti20t_fc =   2.1412e-01
+ dvsat_nfeti20t_fc =   0.0000e+00
+ dcgdx1_nfeti20t_fc =   0.0000e+00
+ dvth0_nfeti20t_fc =   2.5570e-02
+ dtox_nfeti20t_fc =   0.0000e+00
+ dbeta2_nfeti20t_fc =  -3.8748e-01
+ dvth2_nfeti20t_fc =   2.1406e-01
+ dxw_nfeti20t_fc =   0.0000e+00
+ ddvt0_nfeti20t_fc =   0.0000e+00
+ drj_nfeti20t_fc =   3.2086e-02
+ ddlc_nfeti20t_fc =   0.0000e+00
+ dk2_nfeti20t_fc =   0.0000e+00
+ dxl_nfeti20t_fc =   0.0000e+00
+ duo_nfeti20t_fc =  -9.5459e+00
.endl sf_nfeti20t

.lib fff_nfeti20t
.param
+ dbeta1_nfeti20t_fc =   1.6360e+00
+ dcj_nfeti20t_fc =   0.0000e+00
+ dcgso_nfeti20t_fc =   0.0000e+00
+ dk1_nfeti20t_fc =   0.0000e+00
+ dvth1_nfeti20t_fc =  -3.7642e-01
+ dvsat_nfeti20t_fc =   0.0000e+00
+ dcgdx1_nfeti20t_fc =   0.0000e+00
+ dvth0_nfeti20t_fc =  -3.2962e-02
+ dtox_nfeti20t_fc =  -1.5000e-10
+ dbeta2_nfeti20t_fc =   4.6904e-01
+ dvth2_nfeti20t_fc =  -8.6833e-03
+ dxw_nfeti20t_fc =   0.0000e+00
+ ddvt0_nfeti20t_fc =   3.6781e+00
+ drj_nfeti20t_fc =  -1.3500e-03
+ ddlc_nfeti20t_fc =   0.0000e+00
+ dk2_nfeti20t_fc =   0.0000e+00
+ dxl_nfeti20t_fc =   0.0000e+00
+ duo_nfeti20t_fc =   7.8832e+00
.endl fff_nfeti20t

.lib ssf_nfeti20t
.param
+ dbeta1_nfeti20t_fc =  -1.6360e+00
+ dcj_nfeti20t_fc =   0.0000e+00
+ dcgso_nfeti20t_fc =   0.0000e+00
+ dk1_nfeti20t_fc =   0.0000e+00
+ dvth1_nfeti20t_fc =   2.7102e-01
+ dvsat_nfeti20t_fc =   0.0000e+00
+ dcgdx1_nfeti20t_fc =   0.0000e+00
+ dvth0_nfeti20t_fc =   3.0453e-02
+ dtox_nfeti20t_fc =   1.5000e-10
+ dbeta2_nfeti20t_fc =  -4.6920e-01
+ dvth2_nfeti20t_fc =   2.5538e-01
+ dxw_nfeti20t_fc =   0.0000e+00
+ ddvt0_nfeti20t_fc =  -4.0940e+00
+ drj_nfeti20t_fc =   1.6254e-03
+ ddlc_nfeti20t_fc =   0.0000e+00
+ dk2_nfeti20t_fc =   0.0000e+00
+ dxl_nfeti20t_fc =   0.0000e+00
+ duo_nfeti20t_fc =  -1.1559e+01
.endl ssf_nfeti20t

.lib tt_pfet20t
.param
+ dbeta1_pfet20t_fc =   0.0000e+00
+ dcj_pfet20t_fc =   0.0000e+00
+ dcgso_pfet20t_fc =   0.0000e+00
+ dk1_pfet20t_fc =   0.0000e+00
+ dvth1_pfet20t_fc =   0.0000e+00
+ dvsat_pfet20t_fc =   0.0000e+00
+ dcgdx1_pfet20t_fc =   0.0000e+00
+ dvth0_pfet20t_fc =   0.0000e+00
+ dtox_pfet20t_fc =   0.0000e+00
+ dbeta2_pfet20t_fc =   0.0000e+00
+ dvth2_pfet20t_fc =   0.0000e+00
+ dxw_pfet20t_fc =   0.0000e+00
+ ddvt0_pfet20t_fc =   0.0000e+00
+ drj_pfet20t_fc =   0.0000e+00
+ ddlc_pfet20t_fc =   0.0000e+00
+ dk2_pfet20t_fc =   0.0000e+00
+ dxl_pfet20t_fc =   0.0000e+00
+ duo_pfet20t_fc =   0.0000e+00
.endl tt_pfet20t

.lib ff_pfet20t
.param
+ dbeta1_pfet20t_fc =   2.1140e-01
+ dcj_pfet20t_fc =   0.0000e+00
+ dcgso_pfet20t_fc =   0.0000e+00
+ dk1_pfet20t_fc =   0.0000e+00
+ dvth1_pfet20t_fc =  -6.9100e-01
+ dvsat_pfet20t_fc =   0.0000e+00
+ dcgdx1_pfet20t_fc =   0.0000e+00
+ dvth0_pfet20t_fc =   4.8621e-02
+ dtox_pfet20t_fc =  -1.5000e-10
+ dbeta2_pfet20t_fc =   4.3030e-02
+ dvth2_pfet20t_fc =  -3.0475e+00
+ dxw_pfet20t_fc =   0.0000e+00
+ ddvt0_pfet20t_fc =   1.0460e-01
+ drj_pfet20t_fc =  -9.4390e-01
+ ddlc_pfet20t_fc =   0.0000e+00
+ dk2_pfet20t_fc =   0.0000e+00
+ dxl_pfet20t_fc =   0.0000e+00
+ duo_pfet20t_fc =   5.5959e+00
.endl ff_pfet20t

.lib ss_pfet20t
.param
+ dbeta1_pfet20t_fc =  -2.1140e-01
+ dcj_pfet20t_fc =   0.0000e+00
+ dcgso_pfet20t_fc =   0.0000e+00
+ dk1_pfet20t_fc =   0.0000e+00
+ dvth1_pfet20t_fc =   1.2065e+00
+ dvsat_pfet20t_fc =   0.0000e+00
+ dcgdx1_pfet20t_fc =   0.0000e+00
+ dvth0_pfet20t_fc =  -4.9868e-02
+ dtox_pfet20t_fc =   1.5000e-10
+ dbeta2_pfet20t_fc =  -4.3030e-02
+ dvth2_pfet20t_fc =   2.2942e+00
+ dxw_pfet20t_fc =   0.0000e+00
+ ddvt0_pfet20t_fc =  -7.9110e-02
+ drj_pfet20t_fc =   3.1463e-02
+ ddlc_pfet20t_fc =   0.0000e+00
+ dk2_pfet20t_fc =   0.0000e+00
+ dxl_pfet20t_fc =   0.0000e+00
+ duo_pfet20t_fc =  -5.2257e+00
.endl ss_pfet20t

.lib fs_pfet20t
.param
+ dbeta1_pfet20t_fc =  -1.5566e-01
+ dcj_pfet20t_fc =   0.0000e+00
+ dcgso_pfet20t_fc =   0.0000e+00
+ dk1_pfet20t_fc =   0.0000e+00
+ dvth1_pfet20t_fc =   8.7994e-01
+ dvsat_pfet20t_fc =   0.0000e+00
+ dcgdx1_pfet20t_fc =   0.0000e+00
+ dvth0_pfet20t_fc =  -3.8803e-02
+ dtox_pfet20t_fc =   0.0000e+00
+ dbeta2_pfet20t_fc =  -3.1685e-02
+ dvth2_pfet20t_fc =   1.7055e+00
+ dxw_pfet20t_fc =   0.0000e+00
+ ddvt0_pfet20t_fc =   2.9300e-02
+ drj_pfet20t_fc =   5.9611e-01
+ ddlc_pfet20t_fc =   0.0000e+00
+ dk2_pfet20t_fc =   0.0000e+00
+ dxl_pfet20t_fc =   0.0000e+00
+ duo_pfet20t_fc =  -4.0027e+00
.endl fs_pfet20t

.lib sf_pfet20t
.param
+ dbeta1_pfet20t_fc =   1.4976e-01
+ dcj_pfet20t_fc =   0.0000e+00
+ dcgso_pfet20t_fc =   0.0000e+00
+ dk1_pfet20t_fc =   0.0000e+00
+ dvth1_pfet20t_fc =  -1.0272e+00
+ dvsat_pfet20t_fc =   0.0000e+00
+ dcgdx1_pfet20t_fc =   0.0000e+00
+ dvth0_pfet20t_fc =   3.7331e-02
+ dtox_pfet20t_fc =   0.0000e+00
+ dbeta2_pfet20t_fc =   4.0645e-03
+ dvth2_pfet20t_fc =  -2.5044e+00
+ dxw_pfet20t_fc =   0.0000e+00
+ ddvt0_pfet20t_fc =   0.0000e+00
+ drj_pfet20t_fc =  -1.0374e-01
+ ddlc_pfet20t_fc =   0.0000e+00
+ dk2_pfet20t_fc =   0.0000e+00
+ dxl_pfet20t_fc =   0.0000e+00
+ duo_pfet20t_fc =   3.6276e+00
.endl sf_pfet20t

.lib fff_pfet20t
.param
+ dbeta1_pfet20t_fc =   2.1140e-01
+ dcj_pfet20t_fc =   0.0000e+00
+ dcgso_pfet20t_fc =   0.0000e+00
+ dk1_pfet20t_fc =   0.0000e+00
+ dvth1_pfet20t_fc =  -6.9100e-01
+ dvsat_pfet20t_fc =   0.0000e+00
+ dcgdx1_pfet20t_fc =   0.0000e+00
+ dvth0_pfet20t_fc =   4.8621e-02
+ dtox_pfet20t_fc =  -1.5000e-10
+ dbeta2_pfet20t_fc =   4.3030e-02
+ dvth2_pfet20t_fc =  -3.0475e+00
+ dxw_pfet20t_fc =   0.0000e+00
+ ddvt0_pfet20t_fc =   1.0460e-01
+ drj_pfet20t_fc =  -9.4390e-01
+ ddlc_pfet20t_fc =   0.0000e+00
+ dk2_pfet20t_fc =   0.0000e+00
+ dxl_pfet20t_fc =   0.0000e+00
+ duo_pfet20t_fc =   5.5959e+00
.endl fff_pfet20t

.lib ssf_pfet20t
.param
+ dbeta1_pfet20t_fc =  -2.1140e-01
+ dcj_pfet20t_fc =   0.0000e+00
+ dcgso_pfet20t_fc =   0.0000e+00
+ dk1_pfet20t_fc =   0.0000e+00
+ dvth1_pfet20t_fc =   1.2065e+00
+ dvsat_pfet20t_fc =   0.0000e+00
+ dcgdx1_pfet20t_fc =   0.0000e+00
+ dvth0_pfet20t_fc =  -4.9868e-02
+ dtox_pfet20t_fc =   1.5000e-10
+ dbeta2_pfet20t_fc =  -4.3030e-02
+ dvth2_pfet20t_fc =   2.2942e+00
+ dxw_pfet20t_fc =   0.0000e+00
+ ddvt0_pfet20t_fc =  -7.9110e-02
+ drj_pfet20t_fc =   3.1463e-02
+ ddlc_pfet20t_fc =   0.0000e+00
+ dk2_pfet20t_fc =   0.0000e+00
+ dxl_pfet20t_fc =   0.0000e+00
+ duo_pfet20t_fc =  -5.2257e+00
.endl ssf_pfet20t


.lib tt_nfeti50t
.param
+ dbeta1_nfeti50t_fc =   0.0000e+00
+ dcj_nfeti50t_fc =   0.0000e+00
+ dcgso_nfeti50t_fc =   0.0000e+00
+ dk1_nfeti50t_fc =   0.0000e+00
+ dvth1_nfeti50t_fc =   0.0000e+00
+ dvsat_nfeti50t_fc =   0.0000e+00
+ dcgdx1_nfeti50t_fc =   0.0000e+00
+ dvth0_nfeti50t_fc =   0.0000e+00
+ dtox_nfeti50t_fc =   0.0000e+00
+ dbeta2_nfeti50t_fc =   0.0000e+00
+ dvth2_nfeti50t_fc =   0.0000e+00
+ dxw_nfeti50t_fc =   0.0000e+00
+ ddvt0_nfeti50t_fc =   0.0000e+00
+ drj_nfeti50t_fc =   0.0000e+00
+ ddlc_nfeti50t_fc =   0.0000e+00
+ dk2_nfeti50t_fc =   0.0000e+00
+ dxl_nfeti50t_fc =   0.0000e+00
+ duo_nfeti50t_fc =   0.0000e+00
.endl tt_nfeti50t

.lib ff_nfeti50t
.param
+ dbeta1_nfeti50t_fc =   7.5130e-01
+ dcj_nfeti50t_fc =   0.0000e+00
+ dcgso_nfeti50t_fc =   0.0000e+00
+ dk1_nfeti50t_fc =   0.0000e+00
+ dvth1_nfeti50t_fc =  -9.6250e-02
+ dvsat_nfeti50t_fc =   0.0000e+00
+ dcgdx1_nfeti50t_fc =   0.0000e+00
+ dvth0_nfeti50t_fc =  -3.1198e-02
+ dtox_nfeti50t_fc =  -1.5000e-10
+ dbeta2_nfeti50t_fc =   4.8664e-02
+ dvth2_nfeti50t_fc =  -1.7264e-01
+ dxw_nfeti50t_fc =   0.0000e+00
+ ddvt0_nfeti50t_fc =   8.8707e+00
+ drj_nfeti50t_fc =  -7.0250e-03
+ ddlc_nfeti50t_fc =   0.0000e+00
+ dk2_nfeti50t_fc =   0.0000e+00
+ dxl_nfeti50t_fc =   0.0000e+00
+ duo_nfeti50t_fc =   1.2398e+01
.endl ff_nfeti50t

.lib ss_nfeti50t
.param
+ dbeta1_nfeti50t_fc =  -6.8994e-01
+ dcj_nfeti50t_fc =   0.0000e+00
+ dcgso_nfeti50t_fc =   0.0000e+00
+ dk1_nfeti50t_fc =   0.0000e+00
+ dvth1_nfeti50t_fc =   9.3010e-02
+ dvsat_nfeti50t_fc =   0.0000e+00
+ dcgdx1_nfeti50t_fc =   0.0000e+00
+ dvth0_nfeti50t_fc =   2.6518e-02
+ dtox_nfeti50t_fc =   1.5000e-10
+ dbeta2_nfeti50t_fc =  -4.6230e-02
+ dvth2_nfeti50t_fc =   5.0803e-01
+ dxw_nfeti50t_fc =   0.0000e+00
+ ddvt0_nfeti50t_fc =  -1.6854e+01
+ drj_nfeti50t_fc =   1.5651e-01
+ ddlc_nfeti50t_fc =   0.0000e+00
+ dk2_nfeti50t_fc =   0.0000e+00
+ dxl_nfeti50t_fc =   0.0000e+00
+ duo_nfeti50t_fc =  -1.1616e+01
.endl ss_nfeti50t

.lib fs_nfeti50t
.param
+ dbeta1_nfeti50t_fc =   6.9424e-01
+ dcj_nfeti50t_fc =   0.0000e+00
+ dcgso_nfeti50t_fc =   0.0000e+00
+ dk1_nfeti50t_fc =   0.0000e+00
+ dvth1_nfeti50t_fc =  -8.8940e-02
+ dvsat_nfeti50t_fc =   0.0000e+00
+ dcgdx1_nfeti50t_fc =   0.0000e+00
+ dvth0_nfeti50t_fc =  -2.8550e-02
+ dtox_nfeti50t_fc =   0.0000e+00
+ dbeta2_nfeti50t_fc =   4.4968e-02
+ dvth2_nfeti50t_fc =  -1.5953e-01
+ dxw_nfeti50t_fc =   0.0000e+00
+ ddvt0_nfeti50t_fc =   0.0000e+00
+ drj_nfeti50t_fc =  -6.4915e-03
+ ddlc_nfeti50t_fc =   0.0000e+00
+ dk2_nfeti50t_fc =   0.0000e+00
+ dxl_nfeti50t_fc =   0.0000e+00
+ duo_nfeti50t_fc =   1.1457e+01
.endl fs_nfeti50t

.lib sf_nfeti50t
.param
+ dbeta1_nfeti50t_fc =  -5.6326e-01
+ dcj_nfeti50t_fc =   0.0000e+00
+ dcgso_nfeti50t_fc =   0.0000e+00
+ dk1_nfeti50t_fc =   0.0000e+00
+ dvth1_nfeti50t_fc =   7.5931e-02
+ dvsat_nfeti50t_fc =   0.0000e+00
+ dcgdx1_nfeti50t_fc =   0.0000e+00
+ dvth0_nfeti50t_fc =   2.8598e-02
+ dtox_nfeti50t_fc =   0.0000e+00
+ dbeta2_nfeti50t_fc =  -3.7741e-02
+ dvth2_nfeti50t_fc =   4.1475e-01
+ dxw_nfeti50t_fc =   0.0000e+00
+ ddvt0_nfeti50t_fc =   0.0000e+00
+ drj_nfeti50t_fc =   1.2777e-01
+ ddlc_nfeti50t_fc =   0.0000e+00
+ dk2_nfeti50t_fc =   0.0000e+00
+ dxl_nfeti50t_fc =   0.0000e+00
+ duo_nfeti50t_fc =  -9.4827e+00
.endl sf_nfeti50t

.lib fff_nfeti50t
.param
+ dbeta1_nfeti50t_fc =   7.5130e-01
+ dcj_nfeti50t_fc =   0.0000e+00
+ dcgso_nfeti50t_fc =   0.0000e+00
+ dk1_nfeti50t_fc =   0.0000e+00
+ dvth1_nfeti50t_fc =  -9.6250e-02
+ dvsat_nfeti50t_fc =   0.0000e+00
+ dcgdx1_nfeti50t_fc =   0.0000e+00
+ dvth0_nfeti50t_fc =  -3.1198e-02
+ dtox_nfeti50t_fc =  -1.5000e-10
+ dbeta2_nfeti50t_fc =   4.8664e-02
+ dvth2_nfeti50t_fc =  -1.7264e-01
+ dxw_nfeti50t_fc =   0.0000e+00
+ ddvt0_nfeti50t_fc =   8.8707e+00
+ drj_nfeti50t_fc =  -7.0250e-03
+ ddlc_nfeti50t_fc =   0.0000e+00
+ dk2_nfeti50t_fc =   0.0000e+00
+ dxl_nfeti50t_fc =   0.0000e+00
+ duo_nfeti50t_fc =   1.2398e+01
.endl fff_nfeti50t

.lib ssf_nfeti50t
.param
+ dbeta1_nfeti50t_fc =  -6.8994e-01
+ dcj_nfeti50t_fc =   0.0000e+00
+ dcgso_nfeti50t_fc =   0.0000e+00
+ dk1_nfeti50t_fc =   0.0000e+00
+ dvth1_nfeti50t_fc =   9.3010e-02
+ dvsat_nfeti50t_fc =   0.0000e+00
+ dcgdx1_nfeti50t_fc =   0.0000e+00
+ dvth0_nfeti50t_fc =   2.6518e-02
+ dtox_nfeti50t_fc =   1.5000e-10
+ dbeta2_nfeti50t_fc =  -4.6230e-02
+ dvth2_nfeti50t_fc =   5.0803e-01
+ dxw_nfeti50t_fc =   0.0000e+00
+ ddvt0_nfeti50t_fc =  -1.6854e+01
+ drj_nfeti50t_fc =   1.5651e-01
+ ddlc_nfeti50t_fc =   0.0000e+00
+ dk2_nfeti50t_fc =   0.0000e+00
+ dxl_nfeti50t_fc =   0.0000e+00
+ duo_nfeti50t_fc =  -1.1616e+01
.endl ssf_nfeti50t

.lib tt_pfet50t
.param
+ dbeta1_pfet50t_fc =   0.0000e+00
+ dcj_pfet50t_fc =   0.0000e+00
+ dcgso_pfet50t_fc =   0.0000e+00
+ dk1_pfet50t_fc =   0.0000e+00
+ dvth1_pfet50t_fc =   0.0000e+00
+ dvsat_pfet50t_fc =   0.0000e+00
+ dcgdx1_pfet50t_fc =   0.0000e+00
+ dvth0_pfet50t_fc =   0.0000e+00
+ dtox_pfet50t_fc =   0.0000e+00
+ dbeta2_pfet50t_fc =   0.0000e+00
+ dvth2_pfet50t_fc =   0.0000e+00
+ dxw_pfet50t_fc =   0.0000e+00
+ ddvt0_pfet50t_fc =   0.0000e+00
+ drj_pfet50t_fc =   0.0000e+00
+ ddlc_pfet50t_fc =   0.0000e+00
+ dk2_pfet50t_fc =   0.0000e+00
+ dxl_pfet50t_fc =   0.0000e+00
+ duo_pfet50t_fc =   0.0000e+00
.endl tt_pfet50t

.lib ff_pfet50t
.param
+ dbeta1_pfet50t_fc =   8.4410e-02
+ dcj_pfet50t_fc =   0.0000e+00
+ dcgso_pfet50t_fc =   0.0000e+00
+ dk1_pfet50t_fc =   0.0000e+00
+ dvth1_pfet50t_fc =  -5.4617e-01
+ dvsat_pfet50t_fc =   0.0000e+00
+ dcgdx1_pfet50t_fc =   0.0000e+00
+ dvth0_pfet50t_fc =   4.0362e-02
+ dtox_pfet50t_fc =  -1.5000e-10
+ dbeta2_pfet50t_fc =   2.4385e-02
+ dvth2_pfet50t_fc =  -1.3870e+00
+ dxw_pfet50t_fc =   0.0000e+00
+ ddvt0_pfet50t_fc =   1.0292e-01
+ drj_pfet50t_fc =  -4.9485e-01
+ ddlc_pfet50t_fc =   0.0000e+00
+ dk2_pfet50t_fc =   0.0000e+00
+ dxl_pfet50t_fc =   0.0000e+00
+ duo_pfet50t_fc =   3.5747e+00
.endl ff_pfet50t

.lib ss_pfet50t
.param
+ dbeta1_pfet50t_fc =  -6.9104e-02
+ dcj_pfet50t_fc =   0.0000e+00
+ dcgso_pfet50t_fc =   0.0000e+00
+ dk1_pfet50t_fc =   0.0000e+00
+ dvth1_pfet50t_fc =   6.0275e-01
+ dvsat_pfet50t_fc =   0.0000e+00
+ dcgdx1_pfet50t_fc =   0.0000e+00
+ dvth0_pfet50t_fc =  -4.2044e-02
+ dtox_pfet50t_fc =   1.5000e-10
+ dbeta2_pfet50t_fc =  -1.8159e-02
+ dvth2_pfet50t_fc =   2.0703e+00
+ dxw_pfet50t_fc =   0.0000e+00
+ ddvt0_pfet50t_fc =  -1.0562e-01
+ drj_pfet50t_fc =   6.1857e-02
+ ddlc_pfet50t_fc =   0.0000e+00
+ dk2_pfet50t_fc =   0.0000e+00
+ dxl_pfet50t_fc =   0.0000e+00
+ duo_pfet50t_fc =  -4.8595e+00
.endl ss_pfet50t

.lib fs_pfet50t
.param
+ dbeta1_pfet50t_fc =  -5.0823e-02
+ dcj_pfet50t_fc =   0.0000e+00
+ dcgso_pfet50t_fc =   0.0000e+00
+ dk1_pfet50t_fc =   0.0000e+00
+ dvth1_pfet50t_fc =   4.4330e-01
+ dvsat_pfet50t_fc =   0.0000e+00
+ dcgdx1_pfet50t_fc =   0.0000e+00
+ dvth0_pfet50t_fc =  -3.0922e-02
+ dtox_pfet50t_fc =   0.0000e+00
+ dbeta2_pfet50t_fc =  -1.3355e-02
+ dvth2_pfet50t_fc =   1.5226e+00
+ dxw_pfet50t_fc =   0.0000e+00
+ ddvt0_pfet50t_fc =  -7.3125e-02
+ drj_pfet50t_fc =   4.5493e-02
+ ddlc_pfet50t_fc =   0.0000e+00
+ dk2_pfet50t_fc =   0.0000e+00
+ dxl_pfet50t_fc =   0.0000e+00
+ duo_pfet50t_fc =  -3.5740e+00
.endl fs_pfet50t

.lib sf_pfet50t
.param
+ dbeta1_pfet50t_fc =   6.6368e-02
+ dcj_pfet50t_fc =   0.0000e+00
+ dcgso_pfet50t_fc =   0.0000e+00
+ dk1_pfet50t_fc =   0.0000e+00
+ dvth1_pfet50t_fc =  -4.2943e-01
+ dvsat_pfet50t_fc =   0.0000e+00
+ dcgdx1_pfet50t_fc =   0.0000e+00
+ dvth0_pfet50t_fc =   4.1203e-02
+ dtox_pfet50t_fc =   0.0000e+00
+ dbeta2_pfet50t_fc =   1.9173e-02
+ dvth2_pfet50t_fc =  -1.0905e+00
+ dxw_pfet50t_fc =   0.0000e+00
+ ddvt0_pfet50t_fc =  -5.4167e-03
+ drj_pfet50t_fc =  -3.8908e-01
+ ddlc_pfet50t_fc =   0.0000e+00
+ dk2_pfet50t_fc =   0.0000e+00
+ dxl_pfet50t_fc =   0.0000e+00
+ duo_pfet50t_fc =   2.8106e+00
.endl sf_pfet50t

.lib fff_pfet50t
.param
+ dbeta1_pfet50t_fc =   8.4410e-02
+ dcj_pfet50t_fc =   0.0000e+00
+ dcgso_pfet50t_fc =   0.0000e+00
+ dk1_pfet50t_fc =   0.0000e+00
+ dvth1_pfet50t_fc =  -5.4617e-01
+ dvsat_pfet50t_fc =   0.0000e+00
+ dcgdx1_pfet50t_fc =   0.0000e+00
+ dvth0_pfet50t_fc =   4.0362e-02
+ dtox_pfet50t_fc =  -1.5000e-10
+ dbeta2_pfet50t_fc =   2.4385e-02
+ dvth2_pfet50t_fc =  -1.3870e+00
+ dxw_pfet50t_fc =   0.0000e+00
+ ddvt0_pfet50t_fc =   1.0292e-01
+ drj_pfet50t_fc =  -4.9485e-01
+ ddlc_pfet50t_fc =   0.0000e+00
+ dk2_pfet50t_fc =   0.0000e+00
+ dxl_pfet50t_fc =   0.0000e+00
+ duo_pfet50t_fc =   3.5747e+00
.endl fff_pfet50t

.lib ssf_pfet50t
.param
+ dbeta1_pfet50t_fc =  -6.9104e-02
+ dcj_pfet50t_fc =   0.0000e+00
+ dcgso_pfet50t_fc =   0.0000e+00
+ dk1_pfet50t_fc =   0.0000e+00
+ dvth1_pfet50t_fc =   6.0275e-01
+ dvsat_pfet50t_fc =   0.0000e+00
+ dcgdx1_pfet50t_fc =   0.0000e+00
+ dvth0_pfet50t_fc =  -4.2044e-02
+ dtox_pfet50t_fc =   1.5000e-10
+ dbeta2_pfet50t_fc =  -1.8159e-02
+ dvth2_pfet50t_fc =   2.0703e+00
+ dxw_pfet50t_fc =   0.0000e+00
+ ddvt0_pfet50t_fc =  -1.0562e-01
+ drj_pfet50t_fc =   6.1857e-02
+ ddlc_pfet50t_fc =   0.0000e+00
+ dk2_pfet50t_fc =   0.0000e+00
+ dxl_pfet50t_fc =   0.0000e+00
+ duo_pfet50t_fc =  -4.8595e+00
.endl ssf_pfet50t


.lib tt_nfet20mh
.param
+ dbeta1_nfet20mh_fc =   0.0000e+00
+ dcj_nfet20mh_fc =   0.0000e+00
+ dcgso_nfet20mh_fc =   0.0000e+00
+ dk1_nfet20mh_fc =   0.0000e+00
+ dvth1_nfet20mh_fc =   0.0000e+00
+ dvsat_nfet20mh_fc =   0.0000e+00
+ dcgdx1_nfet20mh_fc =   0.0000e+00
+ dvth0_nfet20mh_fc =   0.0000e+00
+ dtox_nfet20mh_fc =   0.0000e+00
+ dbeta2_nfet20mh_fc =   0.0000e+00
+ dvth2_nfet20mh_fc =   0.0000e+00
+ dxw_nfet20mh_fc =   0.0000e+00
+ ddvt0_nfet20mh_fc =   0.0000e+00
+ drj_nfet20mh_fc =   0.0000e+00
+ ddlc_nfet20mh_fc =   0.0000e+00
+ dk2_nfet20mh_fc =   0.0000e+00
+ dxl_nfet20mh_fc =   0.0000e+00
+ duo_nfet20mh_fc =   0.0000e+00
.endl tt_nfet20mh

.lib ff_nfet20mh
.param
+ dbeta1_nfet20mh_fc =   7.3710e+00
+ dcj_nfet20mh_fc =   0.0000e+00
+ dcgso_nfet20mh_fc =   0.0000e+00
+ dk1_nfet20mh_fc =   0.0000e+00
+ dvth1_nfet20mh_fc =  -4.2867e-03
+ dvsat_nfet20mh_fc =   0.0000e+00
+ dcgdx1_nfet20mh_fc =   0.0000e+00
+ dvth0_nfet20mh_fc =  -5.1726e-02
+ dtox_nfet20mh_fc =  -4.0000e-10
+ dbeta2_nfet20mh_fc =   1.6930e+00
+ dvth2_nfet20mh_fc =  -4.6267e-03
+ dxw_nfet20mh_fc =   0.0000e+00
+ ddvt0_nfet20mh_fc =   6.2800e-01
+ drj_nfet20mh_fc =  -4.3357e-01
+ ddlc_nfet20mh_fc =   0.0000e+00
+ dk2_nfet20mh_fc =   0.0000e+00
+ dxl_nfet20mh_fc =  -7.3333e-08
+ duo_nfet20mh_fc =   9.9670e+00
.endl ff_nfet20mh

.lib ss_nfet20mh
.param
+ dbeta1_nfet20mh_fc =  -3.5627e+00
+ dcj_nfet20mh_fc =   0.0000e+00
+ dcgso_nfet20mh_fc =   0.0000e+00
+ dk1_nfet20mh_fc =   0.0000e+00
+ dvth1_nfet20mh_fc =   6.2028e-02
+ dvsat_nfet20mh_fc =   0.0000e+00
+ dcgdx1_nfet20mh_fc =   0.0000e+00
+ dvth0_nfet20mh_fc =   5.1726e-02
+ dtox_nfet20mh_fc =   4.0000e-10
+ dbeta2_nfet20mh_fc =  -2.5710e+00
+ dvth2_nfet20mh_fc =   1.1155e-01
+ dxw_nfet20mh_fc =   0.0000e+00
+ ddvt0_nfet20mh_fc =  -9.4200e-01
+ drj_nfet20mh_fc =   3.7368e-02
+ ddlc_nfet20mh_fc =   0.0000e+00
+ dk2_nfet20mh_fc =   0.0000e+00
+ dxl_nfet20mh_fc =   7.3333e-08
+ duo_nfet20mh_fc =  -9.9670e+00
.endl ss_nfet20mh

.lib fs_nfet20mh
.param
+ dbeta1_nfet20mh_fc =   7.3710e+00
+ dcj_nfet20mh_fc =   0.0000e+00
+ dcgso_nfet20mh_fc =   0.0000e+00
+ dk1_nfet20mh_fc =   0.0000e+00
+ dvth1_nfet20mh_fc =  -4.2867e-03
+ dvsat_nfet20mh_fc =   0.0000e+00
+ dcgdx1_nfet20mh_fc =   0.0000e+00
+ dvth0_nfet20mh_fc =  -5.1726e-02
+ dtox_nfet20mh_fc =   0.0000e+00
+ dbeta2_nfet20mh_fc =   1.6930e+00
+ dvth2_nfet20mh_fc =  -4.6267e-03
+ dxw_nfet20mh_fc =   0.0000e+00
+ ddvt0_nfet20mh_fc =   0.0000e+00
+ drj_nfet20mh_fc =  -4.3357e-01
+ ddlc_nfet20mh_fc =   0.0000e+00
+ dk2_nfet20mh_fc =   0.0000e+00
+ dxl_nfet20mh_fc =   0.0000e+00
+ duo_nfet20mh_fc =   9.9670e+00
.endl fs_nfet20mh

.lib sf_nfet20mh
.param
+ dbeta1_nfet20mh_fc =  -3.5627e+00
+ dcj_nfet20mh_fc =   0.0000e+00
+ dcgso_nfet20mh_fc =   0.0000e+00
+ dk1_nfet20mh_fc =   0.0000e+00
+ dvth1_nfet20mh_fc =   6.2028e-02
+ dvsat_nfet20mh_fc =   0.0000e+00
+ dcgdx1_nfet20mh_fc =   0.0000e+00
+ dvth0_nfet20mh_fc =   5.1726e-02
+ dtox_nfet20mh_fc =   0.0000e+00
+ dbeta2_nfet20mh_fc =  -2.5710e+00
+ dvth2_nfet20mh_fc =   1.1155e-01
+ dxw_nfet20mh_fc =   0.0000e+00
+ ddvt0_nfet20mh_fc =   0.0000e+00
+ drj_nfet20mh_fc =   3.7368e-02
+ ddlc_nfet20mh_fc =   0.0000e+00
+ dk2_nfet20mh_fc =   0.0000e+00
+ dxl_nfet20mh_fc =   0.0000e+00
+ duo_nfet20mh_fc =  -9.9670e+00
.endl sf_nfet20mh

.lib fff_nfet20mh
.param
+ dbeta1_nfet20mh_fc =   7.3710e+00
+ dcj_nfet20mh_fc =   0.0000e+00
+ dcgso_nfet20mh_fc =   0.0000e+00
+ dk1_nfet20mh_fc =   0.0000e+00
+ dvth1_nfet20mh_fc =  -4.2867e-03
+ dvsat_nfet20mh_fc =   0.0000e+00
+ dcgdx1_nfet20mh_fc =   0.0000e+00
+ dvth0_nfet20mh_fc =  -5.1726e-02
+ dtox_nfet20mh_fc =  -4.0000e-10
+ dbeta2_nfet20mh_fc =   1.6930e+00
+ dvth2_nfet20mh_fc =  -4.6267e-03
+ dxw_nfet20mh_fc =   0.0000e+00
+ ddvt0_nfet20mh_fc =   6.2800e-01
+ drj_nfet20mh_fc =  -4.3357e-01
+ ddlc_nfet20mh_fc =   0.0000e+00
+ dk2_nfet20mh_fc =   0.0000e+00
+ dxl_nfet20mh_fc =  -7.3333e-08
+ duo_nfet20mh_fc =   9.9670e+00
.endl fff_nfet20mh

.lib ssf_nfet20mh
.param
+ dbeta1_nfet20mh_fc =  -3.5627e+00
+ dcj_nfet20mh_fc =   0.0000e+00
+ dcgso_nfet20mh_fc =   0.0000e+00
+ dk1_nfet20mh_fc =   0.0000e+00
+ dvth1_nfet20mh_fc =   6.2028e-02
+ dvsat_nfet20mh_fc =   0.0000e+00
+ dcgdx1_nfet20mh_fc =   0.0000e+00
+ dvth0_nfet20mh_fc =   5.1726e-02
+ dtox_nfet20mh_fc =   4.0000e-10
+ dbeta2_nfet20mh_fc =  -2.5710e+00
+ dvth2_nfet20mh_fc =   1.1155e-01
+ dxw_nfet20mh_fc =   0.0000e+00
+ ddvt0_nfet20mh_fc =  -9.4200e-01
+ drj_nfet20mh_fc =   3.7368e-02
+ ddlc_nfet20mh_fc =   0.0000e+00
+ dk2_nfet20mh_fc =   0.0000e+00
+ dxl_nfet20mh_fc =   7.3333e-08
+ duo_nfet20mh_fc =  -9.9670e+00
.endl ssf_nfet20mh


.lib tt_nfeti25m
.param
+ dbeta1_nfeti25m_fc =   0.0000e+00
+ dcj_nfeti25m_fc =   0.0000e+00
+ dcgso_nfeti25m_fc =   0.0000e+00
+ dk1_nfeti25m_fc =   0.0000e+00
+ dvth1_nfeti25m_fc =   0.0000e+00
+ dvsat_nfeti25m_fc =   0.0000e+00
+ dcgdx1_nfeti25m_fc =   0.0000e+00
+ dvth0_nfeti25m_fc =   0.0000e+00
+ dtox_nfeti25m_fc =   0.0000e+00
+ dbeta2_nfeti25m_fc =   0.0000e+00
+ dvth2_nfeti25m_fc =   0.0000e+00
+ dxw_nfeti25m_fc =   0.0000e+00
+ ddvt0_nfeti25m_fc =   0.0000e+00
+ drj_nfeti25m_fc =   0.0000e+00
+ ddlc_nfeti25m_fc =   0.0000e+00
+ dk2_nfeti25m_fc =   0.0000e+00
+ dxl_nfeti25m_fc =   0.0000e+00
+ duo_nfeti25m_fc =   0.0000e+00
.endl tt_nfeti25m

.lib ff_nfeti25m
.param
+ dbeta1_nfeti25m_fc =   3.0842e+00
+ dcj_nfeti25m_fc =   0.0000e+00
+ dcgso_nfeti25m_fc =   0.0000e+00
+ dk1_nfeti25m_fc =   0.0000e+00
+ dvth1_nfeti25m_fc =  -4.2400e-02
+ dvsat_nfeti25m_fc =   0.0000e+00
+ dcgdx1_nfeti25m_fc =   0.0000e+00
+ dvth0_nfeti25m_fc =  -5.1572e-02
+ dtox_nfeti25m_fc =  -4.0000e-10
+ dbeta2_nfeti25m_fc =   1.9714e-01
+ dvth2_nfeti25m_fc =  -3.3250e-01
+ dxw_nfeti25m_fc =   0.0000e+00
+ ddvt0_nfeti25m_fc =   7.8480e-01
+ drj_nfeti25m_fc =  -1.7767e-02
+ ddlc_nfeti25m_fc =   0.0000e+00
+ dk2_nfeti25m_fc =   0.0000e+00
+ dxl_nfeti25m_fc =  -7.3333e-08
+ duo_nfeti25m_fc =   8.1843e+00
.endl ff_nfeti25m

.lib ss_nfeti25m
.param
+ dbeta1_nfeti25m_fc =  -3.3191e+00
+ dcj_nfeti25m_fc =   0.0000e+00
+ dcgso_nfeti25m_fc =   0.0000e+00
+ dk1_nfeti25m_fc =   0.0000e+00
+ dvth1_nfeti25m_fc =   4.2259e-02
+ dvsat_nfeti25m_fc =   0.0000e+00
+ dcgdx1_nfeti25m_fc =   0.0000e+00
+ dvth0_nfeti25m_fc =   4.7048e-02
+ dtox_nfeti25m_fc =   4.0000e-10
+ dbeta2_nfeti25m_fc =  -1.9714e-01
+ dvth2_nfeti25m_fc =   3.3250e-01
+ dxw_nfeti25m_fc =   0.0000e+00
+ ddvt0_nfeti25m_fc =  -1.1772e+00
+ drj_nfeti25m_fc =   1.7785e-02
+ ddlc_nfeti25m_fc =   0.0000e+00
+ dk2_nfeti25m_fc =   0.0000e+00
+ dxl_nfeti25m_fc =   7.3333e-08
+ duo_nfeti25m_fc =  -1.0606e+01
.endl ss_nfeti25m

.lib fs_nfeti25m
.param
+ dbeta1_nfeti25m_fc =   2.6399e+00
+ dcj_nfeti25m_fc =   0.0000e+00
+ dcgso_nfeti25m_fc =   0.0000e+00
+ dk1_nfeti25m_fc =   0.0000e+00
+ dvth1_nfeti25m_fc =  -3.6134e-02
+ dvsat_nfeti25m_fc =   0.0000e+00
+ dcgdx1_nfeti25m_fc =   0.0000e+00
+ dvth0_nfeti25m_fc =  -4.6465e-02
+ dtox_nfeti25m_fc =   0.0000e+00
+ dbeta2_nfeti25m_fc =   1.6874e-01
+ dvth2_nfeti25m_fc =  -2.8460e-01
+ dxw_nfeti25m_fc =   0.0000e+00
+ ddvt0_nfeti25m_fc =   0.0000e+00
+ drj_nfeti25m_fc =  -1.5207e-02
+ ddlc_nfeti25m_fc =   0.0000e+00
+ dk2_nfeti25m_fc =   0.0000e+00
+ dxl_nfeti25m_fc =   0.0000e+00
+ duo_nfeti25m_fc =   7.0052e+00
.endl fs_nfeti25m

.lib sf_nfeti25m
.param
+ dbeta1_nfeti25m_fc =  -2.9106e+00
+ dcj_nfeti25m_fc =   0.0000e+00
+ dcgso_nfeti25m_fc =   0.0000e+00
+ dk1_nfeti25m_fc =   0.0000e+00
+ dvth1_nfeti25m_fc =   3.4063e-02
+ dvsat_nfeti25m_fc =   0.0000e+00
+ dcgdx1_nfeti25m_fc =   0.0000e+00
+ dvth0_nfeti25m_fc =   4.3758e-02
+ dtox_nfeti25m_fc =   0.0000e+00
+ dbeta2_nfeti25m_fc =  -1.5891e-01
+ dvth2_nfeti25m_fc =   2.6802e-01
+ dxw_nfeti25m_fc =   0.0000e+00
+ ddvt0_nfeti25m_fc =   0.0000e+00
+ drj_nfeti25m_fc =   1.4336e-02
+ ddlc_nfeti25m_fc =   0.0000e+00
+ dk2_nfeti25m_fc =   0.0000e+00
+ dxl_nfeti25m_fc =   0.0000e+00
+ duo_nfeti25m_fc =  -8.5492e+00
.endl sf_nfeti25m

.lib fff_nfeti25m
.param
+ dbeta1_nfeti25m_fc =   3.0842e+00
+ dcj_nfeti25m_fc =   0.0000e+00
+ dcgso_nfeti25m_fc =   0.0000e+00
+ dk1_nfeti25m_fc =   0.0000e+00
+ dvth1_nfeti25m_fc =  -4.2400e-02
+ dvsat_nfeti25m_fc =   0.0000e+00
+ dcgdx1_nfeti25m_fc =   0.0000e+00
+ dvth0_nfeti25m_fc =  -5.1572e-02
+ dtox_nfeti25m_fc =  -4.0000e-10
+ dbeta2_nfeti25m_fc =   1.9714e-01
+ dvth2_nfeti25m_fc =  -3.3250e-01
+ dxw_nfeti25m_fc =   0.0000e+00
+ ddvt0_nfeti25m_fc =   7.8480e-01
+ drj_nfeti25m_fc =  -1.7767e-02
+ ddlc_nfeti25m_fc =   0.0000e+00
+ dk2_nfeti25m_fc =   0.0000e+00
+ dxl_nfeti25m_fc =  -7.3333e-08
+ duo_nfeti25m_fc =   8.1843e+00
.endl fff_nfeti25m

.lib ssf_nfeti25m
.param
+ dbeta1_nfeti25m_fc =  -3.3191e+00
+ dcj_nfeti25m_fc =   0.0000e+00
+ dcgso_nfeti25m_fc =   0.0000e+00
+ dk1_nfeti25m_fc =   0.0000e+00
+ dvth1_nfeti25m_fc =   4.2259e-02
+ dvsat_nfeti25m_fc =   0.0000e+00
+ dcgdx1_nfeti25m_fc =   0.0000e+00
+ dvth0_nfeti25m_fc =   4.7048e-02
+ dtox_nfeti25m_fc =   4.0000e-10
+ dbeta2_nfeti25m_fc =  -1.9714e-01
+ dvth2_nfeti25m_fc =   3.3250e-01
+ dxw_nfeti25m_fc =   0.0000e+00
+ ddvt0_nfeti25m_fc =  -1.1772e+00
+ drj_nfeti25m_fc =   1.7785e-02
+ ddlc_nfeti25m_fc =   0.0000e+00
+ dk2_nfeti25m_fc =   0.0000e+00
+ dxl_nfeti25m_fc =   7.3333e-08
+ duo_nfeti25m_fc =  -1.0606e+01
.endl ssf_nfeti25m

.lib tt_pfet25m
.param
+ dbeta1_pfet25m_fc =   0.0000e+00
+ dcj_pfet25m_fc =   0.0000e+00
+ dcgso_pfet25m_fc =   0.0000e+00
+ dk1_pfet25m_fc =   0.0000e+00
+ dvth1_pfet25m_fc =   0.0000e+00
+ dvsat_pfet25m_fc =   0.0000e+00
+ dcgdx1_pfet25m_fc =   0.0000e+00
+ dvth0_pfet25m_fc =   0.0000e+00
+ dtox_pfet25m_fc =   0.0000e+00
+ dbeta2_pfet25m_fc =   0.0000e+00
+ dvth2_pfet25m_fc =   0.0000e+00
+ dxw_pfet25m_fc =   0.0000e+00
+ ddvt0_pfet25m_fc =   0.0000e+00
+ drj_pfet25m_fc =   0.0000e+00
+ ddlc_pfet25m_fc =   0.0000e+00
+ dk2_pfet25m_fc =   0.0000e+00
+ dxl_pfet25m_fc =   0.0000e+00
+ duo_pfet25m_fc =   0.0000e+00
.endl tt_pfet25m

.lib ff_pfet25m
.param
+ dbeta1_pfet25m_fc =   1.7100e-01
+ dcj_pfet25m_fc =   0.0000e+00
+ dcgso_pfet25m_fc =   0.0000e+00
+ dk1_pfet25m_fc =   0.0000e+00
+ dvth1_pfet25m_fc =  -3.8000e-01
+ dvsat_pfet25m_fc =   0.0000e+00
+ dcgdx1_pfet25m_fc =   0.0000e+00
+ dvth0_pfet25m_fc =   4.7761e-02
+ dtox_pfet25m_fc =  -4.0000e-10
+ dbeta2_pfet25m_fc =   8.2000e-02
+ dvth2_pfet25m_fc =  -3.2500e-01
+ dxw_pfet25m_fc =   3.3333e-07
+ ddvt0_pfet25m_fc =   2.3713e-01
+ drj_pfet25m_fc =  -2.6445e-03
+ ddlc_pfet25m_fc =   0.0000e+00
+ dk2_pfet25m_fc =   0.0000e+00
+ dxl_pfet25m_fc =   0.0000e+00
+ duo_pfet25m_fc =   4.8842e+00
.endl ff_pfet25m

.lib ss_pfet25m
.param
+ dbeta1_pfet25m_fc =  -1.7083e-01
+ dcj_pfet25m_fc =   0.0000e+00
+ dcgso_pfet25m_fc =   0.0000e+00
+ dk1_pfet25m_fc =   0.0000e+00
+ dvth1_pfet25m_fc =   2.5333e-02
+ dvsat_pfet25m_fc =   0.0000e+00
+ dcgdx1_pfet25m_fc =   0.0000e+00
+ dvth0_pfet25m_fc =  -4.6603e-02
+ dtox_pfet25m_fc =   4.0000e-10
+ dbeta2_pfet25m_fc =  -8.2000e-02
+ dvth2_pfet25m_fc =   2.1667e-02
+ dxw_pfet25m_fc =  -3.3333e-07
+ ddvt0_pfet25m_fc =  -4.0800e-02
+ drj_pfet25m_fc =   2.6445e-03
+ ddlc_pfet25m_fc =   0.0000e+00
+ dk2_pfet25m_fc =   0.0000e+00
+ dxl_pfet25m_fc =   0.0000e+00
+ duo_pfet25m_fc =  -6.0463e+00
.endl ss_pfet25m

.lib fs_pfet25m
.param
+ dbeta1_pfet25m_fc =  -1.4090e-01
+ dcj_pfet25m_fc =   0.0000e+00
+ dcgso_pfet25m_fc =   0.0000e+00
+ dk1_pfet25m_fc =   0.0000e+00
+ dvth1_pfet25m_fc =   2.0888e-02
+ dvsat_pfet25m_fc =   0.0000e+00
+ dcgdx1_pfet25m_fc =   0.0000e+00
+ dvth0_pfet25m_fc =  -3.8440e-02
+ dtox_pfet25m_fc =   0.0000e+00
+ dbeta2_pfet25m_fc =  -6.7611e-02
+ dvth2_pfet25m_fc =   1.7865e-02
+ dxw_pfet25m_fc =   0.0000e+00
+ ddvt0_pfet25m_fc =   0.0000e+00
+ drj_pfet25m_fc =   2.1804e-03
+ ddlc_pfet25m_fc =   0.0000e+00
+ dk2_pfet25m_fc =   0.0000e+00
+ dxl_pfet25m_fc =   0.0000e+00
+ duo_pfet25m_fc =  -5.1010e+00
.endl fs_pfet25m

.lib sf_pfet25m
.param
+ dbeta1_pfet25m_fc =   1.4431e-01
+ dcj_pfet25m_fc =   0.0000e+00
+ dcgso_pfet25m_fc =   0.0000e+00
+ dk1_pfet25m_fc =   0.0000e+00
+ dvth1_pfet25m_fc =  -2.1379e-02
+ dvsat_pfet25m_fc =   0.0000e+00
+ dcgdx1_pfet25m_fc =   0.0000e+00
+ dvth0_pfet25m_fc =   4.1066e-02
+ dtox_pfet25m_fc =   0.0000e+00
+ dbeta2_pfet25m_fc =   6.9201e-02
+ dvth2_pfet25m_fc =  -1.8285e-02
+ dxw_pfet25m_fc =   0.0000e+00
+ ddvt0_pfet25m_fc =   0.0000e+00
+ drj_pfet25m_fc =  -2.2317e-03
+ ddlc_pfet25m_fc =   0.0000e+00
+ dk2_pfet25m_fc =   0.0000e+00
+ dxl_pfet25m_fc =   0.0000e+00
+ duo_pfet25m_fc =   4.1550e+00
.endl sf_pfet25m

.lib fff_pfet25m
.param
+ dbeta1_pfet25m_fc =   1.7100e-01
+ dcj_pfet25m_fc =   0.0000e+00
+ dcgso_pfet25m_fc =   0.0000e+00
+ dk1_pfet25m_fc =   0.0000e+00
+ dvth1_pfet25m_fc =  -3.8000e-01
+ dvsat_pfet25m_fc =   0.0000e+00
+ dcgdx1_pfet25m_fc =   0.0000e+00
+ dvth0_pfet25m_fc =   4.7761e-02
+ dtox_pfet25m_fc =  -4.0000e-10
+ dbeta2_pfet25m_fc =   8.2000e-02
+ dvth2_pfet25m_fc =  -3.2500e-01
+ dxw_pfet25m_fc =   3.3333e-07
+ ddvt0_pfet25m_fc =   2.3713e-01
+ drj_pfet25m_fc =  -2.6445e-03
+ ddlc_pfet25m_fc =   0.0000e+00
+ dk2_pfet25m_fc =   0.0000e+00
+ dxl_pfet25m_fc =   0.0000e+00
+ duo_pfet25m_fc =   4.8842e+00
.endl fff_pfet25m

.lib ssf_pfet25m
.param
+ dbeta1_pfet25m_fc =  -1.7083e-01
+ dcj_pfet25m_fc =   0.0000e+00
+ dcgso_pfet25m_fc =   0.0000e+00
+ dk1_pfet25m_fc =   0.0000e+00
+ dvth1_pfet25m_fc =   2.5333e-02
+ dvsat_pfet25m_fc =   0.0000e+00
+ dcgdx1_pfet25m_fc =   0.0000e+00
+ dvth0_pfet25m_fc =  -4.6603e-02
+ dtox_pfet25m_fc =   4.0000e-10
+ dbeta2_pfet25m_fc =  -8.2000e-02
+ dvth2_pfet25m_fc =   2.1667e-02
+ dxw_pfet25m_fc =  -3.3333e-07
+ ddvt0_pfet25m_fc =  -4.0800e-02
+ drj_pfet25m_fc =   2.6445e-03
+ ddlc_pfet25m_fc =   0.0000e+00
+ dk2_pfet25m_fc =   0.0000e+00
+ dxl_pfet25m_fc =   0.0000e+00
+ duo_pfet25m_fc =  -6.0463e+00
.endl ssf_pfet25m


.lib tt_nfeti50m
.param
+ dbeta1_nfeti50m_fc =   0.0000e+00
+ dcj_nfeti50m_fc =   0.0000e+00
+ dcgso_nfeti50m_fc =   0.0000e+00
+ dk1_nfeti50m_fc =   0.0000e+00
+ dvth1_nfeti50m_fc =   0.0000e+00
+ dvsat_nfeti50m_fc =   0.0000e+00
+ dcgdx1_nfeti50m_fc =   0.0000e+00
+ dvth0_nfeti50m_fc =   0.0000e+00
+ dtox_nfeti50m_fc =   0.0000e+00
+ dbeta2_nfeti50m_fc =   0.0000e+00
+ dvth2_nfeti50m_fc =   0.0000e+00
+ dxw_nfeti50m_fc =   0.0000e+00
+ ddvt0_nfeti50m_fc =   0.0000e+00
+ drj_nfeti50m_fc =   0.0000e+00
+ ddlc_nfeti50m_fc =   0.0000e+00
+ dk2_nfeti50m_fc =   0.0000e+00
+ dxl_nfeti50m_fc =   0.0000e+00
+ duo_nfeti50m_fc =   0.0000e+00
.endl tt_nfeti50m

.lib ff_nfeti50m
.param
+ dbeta1_nfeti50m_fc =   5.0170e-01
+ dcj_nfeti50m_fc =   0.0000e+00
+ dcgso_nfeti50m_fc =   0.0000e+00
+ dk1_nfeti50m_fc =   0.0000e+00
+ dvth1_nfeti50m_fc =  -2.5666e-01
+ dvsat_nfeti50m_fc =   0.0000e+00
+ dcgdx1_nfeti50m_fc =   0.0000e+00
+ dvth0_nfeti50m_fc =  -7.4747e-02
+ dtox_nfeti50m_fc =  -4.0000e-10
+ dbeta2_nfeti50m_fc =   6.2275e-02
+ dvth2_nfeti50m_fc =  -6.9080e-01
+ dxw_nfeti50m_fc =   0.0000e+00
+ ddvt0_nfeti50m_fc =   2.6850e-01
+ drj_nfeti50m_fc =  -8.0835e-02
+ ddlc_nfeti50m_fc =   0.0000e+00
+ dk2_nfeti50m_fc =   0.0000e+00
+ dxl_nfeti50m_fc =  -7.3333e-08
+ duo_nfeti50m_fc =   1.1687e+01
.endl ff_nfeti50m

.lib ss_nfeti50m
.param
+ dbeta1_nfeti50m_fc =  -4.1808e-01
+ dcj_nfeti50m_fc =   0.0000e+00
+ dcgso_nfeti50m_fc =   0.0000e+00
+ dk1_nfeti50m_fc =   0.0000e+00
+ dvth1_nfeti50m_fc =   2.5675e-01
+ dvsat_nfeti50m_fc =   0.0000e+00
+ dcgdx1_nfeti50m_fc =   0.0000e+00
+ dvth0_nfeti50m_fc =   6.8518e-02
+ dtox_nfeti50m_fc =   4.0000e-10
+ dbeta2_nfeti50m_fc =  -7.5730e-02
+ dvth2_nfeti50m_fc =   8.0450e-01
+ dxw_nfeti50m_fc =   0.0000e+00
+ ddvt0_nfeti50m_fc =  -4.4750e-01
+ drj_nfeti50m_fc =   1.6007e-01
+ ddlc_nfeti50m_fc =   0.0000e+00
+ dk2_nfeti50m_fc =   0.0000e+00
+ dxl_nfeti50m_fc =   7.3333e-08
+ duo_nfeti50m_fc =  -1.2953e+01
.endl ss_nfeti50m

.lib fs_nfeti50m
.param
+ dbeta1_nfeti50m_fc =   4.0697e-01
+ dcj_nfeti50m_fc =   0.0000e+00
+ dcgso_nfeti50m_fc =   0.0000e+00
+ dk1_nfeti50m_fc =   0.0000e+00
+ dvth1_nfeti50m_fc =  -2.0820e-01
+ dvsat_nfeti50m_fc =   0.0000e+00
+ dcgdx1_nfeti50m_fc =   0.0000e+00
+ dvth0_nfeti50m_fc =  -6.0634e-02
+ dtox_nfeti50m_fc =   0.0000e+00
+ dbeta2_nfeti50m_fc =   5.0517e-02
+ dvth2_nfeti50m_fc =  -5.6037e-01
+ dxw_nfeti50m_fc =   0.0000e+00
+ ddvt0_nfeti50m_fc =   0.0000e+00
+ drj_nfeti50m_fc =  -6.5573e-02
+ ddlc_nfeti50m_fc =   0.0000e+00
+ dk2_nfeti50m_fc =   0.0000e+00
+ dxl_nfeti50m_fc =   0.0000e+00
+ duo_nfeti50m_fc =   9.4801e+00
.endl fs_nfeti50m

.lib sf_nfeti50m
.param
+ dbeta1_nfeti50m_fc =  -3.3706e-01
+ dcj_nfeti50m_fc =   0.0000e+00
+ dcgso_nfeti50m_fc =   0.0000e+00
+ dk1_nfeti50m_fc =   0.0000e+00
+ dvth1_nfeti50m_fc =   2.0699e-01
+ dvsat_nfeti50m_fc =   0.0000e+00
+ dcgdx1_nfeti50m_fc =   0.0000e+00
+ dvth0_nfeti50m_fc =   5.7308e-02
+ dtox_nfeti50m_fc =   0.0000e+00
+ dbeta2_nfeti50m_fc =  -6.1054e-02
+ dvth2_nfeti50m_fc =   6.4859e-01
+ dxw_nfeti50m_fc =   0.0000e+00
+ ddvt0_nfeti50m_fc =   0.0000e+00
+ drj_nfeti50m_fc =   1.2905e-01
+ ddlc_nfeti50m_fc =   0.0000e+00
+ dk2_nfeti50m_fc =   0.0000e+00
+ dxl_nfeti50m_fc =   0.0000e+00
+ duo_nfeti50m_fc =  -1.0443e+01
.endl sf_nfeti50m

.lib fff_nfeti50m
.param
+ dbeta1_nfeti50m_fc =   5.0170e-01
+ dcj_nfeti50m_fc =   0.0000e+00
+ dcgso_nfeti50m_fc =   0.0000e+00
+ dk1_nfeti50m_fc =   0.0000e+00
+ dvth1_nfeti50m_fc =  -2.5666e-01
+ dvsat_nfeti50m_fc =   0.0000e+00
+ dcgdx1_nfeti50m_fc =   0.0000e+00
+ dvth0_nfeti50m_fc =  -7.4747e-02
+ dtox_nfeti50m_fc =  -4.0000e-10
+ dbeta2_nfeti50m_fc =   6.2275e-02
+ dvth2_nfeti50m_fc =  -6.9080e-01
+ dxw_nfeti50m_fc =   0.0000e+00
+ ddvt0_nfeti50m_fc =   2.6850e-01
+ drj_nfeti50m_fc =  -8.0835e-02
+ ddlc_nfeti50m_fc =   0.0000e+00
+ dk2_nfeti50m_fc =   0.0000e+00
+ dxl_nfeti50m_fc =  -7.3333e-08
+ duo_nfeti50m_fc =   1.1687e+01
.endl fff_nfeti50m

.lib ssf_nfeti50m
.param
+ dbeta1_nfeti50m_fc =  -4.1808e-01
+ dcj_nfeti50m_fc =   0.0000e+00
+ dcgso_nfeti50m_fc =   0.0000e+00
+ dk1_nfeti50m_fc =   0.0000e+00
+ dvth1_nfeti50m_fc =   2.5675e-01
+ dvsat_nfeti50m_fc =   0.0000e+00
+ dcgdx1_nfeti50m_fc =   0.0000e+00
+ dvth0_nfeti50m_fc =   6.8518e-02
+ dtox_nfeti50m_fc =   4.0000e-10
+ dbeta2_nfeti50m_fc =  -7.5730e-02
+ dvth2_nfeti50m_fc =   8.0450e-01
+ dxw_nfeti50m_fc =   0.0000e+00
+ ddvt0_nfeti50m_fc =  -4.4750e-01
+ drj_nfeti50m_fc =   1.6007e-01
+ ddlc_nfeti50m_fc =   0.0000e+00
+ dk2_nfeti50m_fc =   0.0000e+00
+ dxl_nfeti50m_fc =   7.3333e-08
+ duo_nfeti50m_fc =  -1.2953e+01
.endl ssf_nfeti50m

.lib tt_pfet50m
.param
+ dbeta1_pfet50m_fc =   0.0000e+00
+ dcj_pfet50m_fc =   0.0000e+00
+ dcgso_pfet50m_fc =   0.0000e+00
+ dk1_pfet50m_fc =   0.0000e+00
+ dvth1_pfet50m_fc =   0.0000e+00
+ dvsat_pfet50m_fc =   0.0000e+00
+ dcgdx1_pfet50m_fc =   0.0000e+00
+ dvth0_pfet50m_fc =   0.0000e+00
+ dtox_pfet50m_fc =   0.0000e+00
+ dbeta2_pfet50m_fc =   0.0000e+00
+ dvth2_pfet50m_fc =   0.0000e+00
+ dxw_pfet50m_fc =   0.0000e+00
+ ddvt0_pfet50m_fc =   0.0000e+00
+ drj_pfet50m_fc =   0.0000e+00
+ ddlc_pfet50m_fc =   0.0000e+00
+ dk2_pfet50m_fc =   0.0000e+00
+ dxl_pfet50m_fc =   0.0000e+00
+ duo_pfet50m_fc =   0.0000e+00
.endl tt_pfet50m

.lib ff_pfet50m
.param
+ dbeta1_pfet50m_fc =   7.2500e-02
+ dcj_pfet50m_fc =   0.0000e+00
+ dcgso_pfet50m_fc =   0.0000e+00
+ dk1_pfet50m_fc =   0.0000e+00
+ dvth1_pfet50m_fc =  -1.2153e-02
+ dvsat_pfet50m_fc =   0.0000e+00
+ dcgdx1_pfet50m_fc =   0.0000e+00
+ dvth0_pfet50m_fc =   4.2480e-02
+ dtox_pfet50m_fc =  -4.0000e-10
+ dbeta2_pfet50m_fc =   6.3414e-04
+ dvth2_pfet50m_fc =  -2.1504e-02
+ dxw_pfet50m_fc =   3.3333e-07
+ ddvt0_pfet50m_fc =   0.0000e+00
+ drj_pfet50m_fc =  -6.3200e-03
+ ddlc_pfet50m_fc =   0.0000e+00
+ dk2_pfet50m_fc =   0.0000e+00
+ dxl_pfet50m_fc =   0.0000e+00
+ duo_pfet50m_fc =   7.1796e+00
.endl ff_pfet50m

.lib ss_pfet50m
.param
+ dbeta1_pfet50m_fc =  -7.2500e-02
+ dcj_pfet50m_fc =   0.0000e+00
+ dcgso_pfet50m_fc =   0.0000e+00
+ dk1_pfet50m_fc =   0.0000e+00
+ dvth1_pfet50m_fc =   1.2153e-02
+ dvsat_pfet50m_fc =   0.0000e+00
+ dcgdx1_pfet50m_fc =   0.0000e+00
+ dvth0_pfet50m_fc =  -4.3466e-02
+ dtox_pfet50m_fc =   4.0000e-10
+ dbeta2_pfet50m_fc =  -1.2688e-02
+ dvth2_pfet50m_fc =   2.0500e-02
+ dxw_pfet50m_fc =  -3.3333e-07
+ ddvt0_pfet50m_fc =   0.0000e+00
+ drj_pfet50m_fc =   6.3200e-03
+ ddlc_pfet50m_fc =   0.0000e+00
+ dk2_pfet50m_fc =   0.0000e+00
+ dxl_pfet50m_fc =   0.0000e+00
+ duo_pfet50m_fc =  -8.7043e+00
.endl ss_pfet50m

.lib fs_pfet50m
.param
+ dbeta1_pfet50m_fc =  -5.8439e-02
+ dcj_pfet50m_fc =   0.0000e+00
+ dcgso_pfet50m_fc =   0.0000e+00
+ dk1_pfet50m_fc =   0.0000e+00
+ dvth1_pfet50m_fc =   1.0180e-02
+ dvsat_pfet50m_fc =   0.0000e+00
+ dcgdx1_pfet50m_fc =   0.0000e+00
+ dvth0_pfet50m_fc =  -3.6492e-02
+ dtox_pfet50m_fc =   0.0000e+00
+ dbeta2_pfet50m_fc =  -7.4594e-03
+ dvth2_pfet50m_fc =   1.7171e-02
+ dxw_pfet50m_fc =   0.0000e+00
+ ddvt0_pfet50m_fc =   0.0000e+00
+ drj_pfet50m_fc =   5.2989e-03
+ ddlc_pfet50m_fc =   0.0000e+00
+ dk2_pfet50m_fc =   0.0000e+00
+ dxl_pfet50m_fc =   0.0000e+00
+ duo_pfet50m_fc =  -7.1582e+00
.endl fs_pfet50m

.lib sf_pfet50m
.param
+ dbeta1_pfet50m_fc =   6.0696e-02
+ dcj_pfet50m_fc =   0.0000e+00
+ dcgso_pfet50m_fc =   0.0000e+00
+ dk1_pfet50m_fc =   0.0000e+00
+ dvth1_pfet50m_fc =  -1.0215e-02
+ dvsat_pfet50m_fc =   0.0000e+00
+ dcgdx1_pfet50m_fc =   0.0000e+00
+ dvth0_pfet50m_fc =   3.7526e-02
+ dtox_pfet50m_fc =   0.0000e+00
+ dbeta2_pfet50m_fc =   1.1604e-02
+ dvth2_pfet50m_fc =  -2.0200e-02
+ dxw_pfet50m_fc =   0.0000e+00
+ ddvt0_pfet50m_fc =   0.0000e+00
+ drj_pfet50m_fc =  -5.2910e-03
+ ddlc_pfet50m_fc =   0.0000e+00
+ dk2_pfet50m_fc =   0.0000e+00
+ dxl_pfet50m_fc =   0.0000e+00
+ duo_pfet50m_fc =   6.5244e+00
.endl sf_pfet50m

.lib fff_pfet50m
.param
+ dbeta1_pfet50m_fc =   7.2500e-02
+ dcj_pfet50m_fc =   0.0000e+00
+ dcgso_pfet50m_fc =   0.0000e+00
+ dk1_pfet50m_fc =   0.0000e+00
+ dvth1_pfet50m_fc =  -1.2153e-02
+ dvsat_pfet50m_fc =   0.0000e+00
+ dcgdx1_pfet50m_fc =   0.0000e+00
+ dvth0_pfet50m_fc =   4.2480e-02
+ dtox_pfet50m_fc =  -4.0000e-10
+ dbeta2_pfet50m_fc =   6.3414e-04
+ dvth2_pfet50m_fc =  -2.1504e-02
+ dxw_pfet50m_fc =   3.3333e-07
+ ddvt0_pfet50m_fc =   0.0000e+00
+ drj_pfet50m_fc =  -6.3200e-03
+ ddlc_pfet50m_fc =   0.0000e+00
+ dk2_pfet50m_fc =   0.0000e+00
+ dxl_pfet50m_fc =   0.0000e+00
+ duo_pfet50m_fc =   7.1796e+00
.endl fff_pfet50m

.lib ssf_pfet50m
.param
+ dbeta1_pfet50m_fc =  -7.2500e-02
+ dcj_pfet50m_fc =   0.0000e+00
+ dcgso_pfet50m_fc =   0.0000e+00
+ dk1_pfet50m_fc =   0.0000e+00
+ dvth1_pfet50m_fc =   1.2153e-02
+ dvsat_pfet50m_fc =   0.0000e+00
+ dcgdx1_pfet50m_fc =   0.0000e+00
+ dvth0_pfet50m_fc =  -4.3466e-02
+ dtox_pfet50m_fc =   4.0000e-10
+ dbeta2_pfet50m_fc =  -1.2688e-02
+ dvth2_pfet50m_fc =   2.0500e-02
+ dxw_pfet50m_fc =  -3.3333e-07
+ ddvt0_pfet50m_fc =   0.0000e+00
+ drj_pfet50m_fc =   6.3200e-03
+ ddlc_pfet50m_fc =   0.0000e+00
+ dk2_pfet50m_fc =   0.0000e+00
+ dxl_pfet50m_fc =   0.0000e+00
+ duo_pfet50m_fc =  -8.7043e+00
.endl ssf_pfet50m


.lib tt_nfeti20h
.param
+ dbeta1_nfeti20h_fc =   0.0000e+00
+ dcj_nfeti20h_fc =   0.0000e+00
+ dcgso_nfeti20h_fc =   0.0000e+00
+ dk1_nfeti20h_fc =   0.0000e+00
+ dvth1_nfeti20h_fc =   0.0000e+00
+ dvsat_nfeti20h_fc =   0.0000e+00
+ dcgdx1_nfeti20h_fc =   0.0000e+00
+ dvth0_nfeti20h_fc =   0.0000e+00
+ dtox_nfeti20h_fc =   0.0000e+00
+ dbeta2_nfeti20h_fc =   0.0000e+00
+ dvth2_nfeti20h_fc =   0.0000e+00
+ dxw_nfeti20h_fc =   0.0000e+00
+ ddvt0_nfeti20h_fc =   0.0000e+00
+ drj_nfeti20h_fc =   0.0000e+00
+ ddlc_nfeti20h_fc =   0.0000e+00
+ dk2_nfeti20h_fc =   0.0000e+00
+ dxl_nfeti20h_fc =   0.0000e+00
+ duo_nfeti20h_fc =   0.0000e+00
.endl tt_nfeti20h

.lib ff_nfeti20h
.param
+ dbeta1_nfeti20h_fc =   3.8965e+00
+ dcj_nfeti20h_fc =   0.0000e+00
+ dcgso_nfeti20h_fc =   0.0000e+00
+ dk1_nfeti20h_fc =   0.0000e+00
+ dvth1_nfeti20h_fc =  -2.0987e-01
+ dvsat_nfeti20h_fc =   0.0000e+00
+ dcgdx1_nfeti20h_fc =   0.0000e+00
+ dvth0_nfeti20h_fc =  -2.4228e-01
+ dtox_nfeti20h_fc =  -2.0000e-09
+ dbeta2_nfeti20h_fc =   3.5220e-01
+ dvth2_nfeti20h_fc =  -3.3344e-01
+ dxw_nfeti20h_fc =   3.3333e-07
+ ddvt0_nfeti20h_fc =   1.2000e+00
+ drj_nfeti20h_fc =  -2.9348e-02
+ ddlc_nfeti20h_fc =   0.0000e+00
+ dk2_nfeti20h_fc =   0.0000e+00
+ dxl_nfeti20h_fc =   0.0000e+00
+ duo_nfeti20h_fc =   1.8887e+01
.endl ff_nfeti20h

.lib ss_nfeti20h
.param
+ dbeta1_nfeti20h_fc =  -2.8639e+00
+ dcj_nfeti20h_fc =   0.0000e+00
+ dcgso_nfeti20h_fc =   0.0000e+00
+ dk1_nfeti20h_fc =   0.0000e+00
+ dvth1_nfeti20h_fc =   2.2756e-01
+ dvsat_nfeti20h_fc =   0.0000e+00
+ dcgdx1_nfeti20h_fc =   0.0000e+00
+ dvth0_nfeti20h_fc =   2.2286e-01
+ dtox_nfeti20h_fc =   2.0000e-09
+ dbeta2_nfeti20h_fc =  -3.5220e-01
+ dvth2_nfeti20h_fc =   3.4763e-01
+ dxw_nfeti20h_fc =  -3.3333e-07
+ ddvt0_nfeti20h_fc =  -1.2000e+00
+ drj_nfeti20h_fc =   6.1745e-02
+ ddlc_nfeti20h_fc =   0.0000e+00
+ dk2_nfeti20h_fc =   0.0000e+00
+ dxl_nfeti20h_fc =   0.0000e+00
+ duo_nfeti20h_fc =  -1.8825e+01
.endl ss_nfeti20h

.lib fs_nfeti20h
.param
+ dbeta1_nfeti20h_fc =   2.9774e+00
+ dcj_nfeti20h_fc =   0.0000e+00
+ dcgso_nfeti20h_fc =   0.0000e+00
+ dk1_nfeti20h_fc =   0.0000e+00
+ dvth1_nfeti20h_fc =  -1.6036e-01
+ dvsat_nfeti20h_fc =   0.0000e+00
+ dcgdx1_nfeti20h_fc =   0.0000e+00
+ dvth0_nfeti20h_fc =  -1.8519e-01
+ dtox_nfeti20h_fc =   0.0000e+00
+ dbeta2_nfeti20h_fc =   2.6912e-01
+ dvth2_nfeti20h_fc =  -2.5479e-01
+ dxw_nfeti20h_fc =   0.0000e+00
+ ddvt0_nfeti20h_fc =   0.0000e+00
+ drj_nfeti20h_fc =  -2.2425e-02
+ ddlc_nfeti20h_fc =   0.0000e+00
+ dk2_nfeti20h_fc =   0.0000e+00
+ dxl_nfeti20h_fc =   0.0000e+00
+ duo_nfeti20h_fc =   1.4432e+01
.endl fs_nfeti20h

.lib sf_nfeti20h
.param
+ dbeta1_nfeti20h_fc =  -2.1263e+00
+ dcj_nfeti20h_fc =   0.0000e+00
+ dcgso_nfeti20h_fc =   0.0000e+00
+ dk1_nfeti20h_fc =   0.0000e+00
+ dvth1_nfeti20h_fc =   1.6894e-01
+ dvsat_nfeti20h_fc =   0.0000e+00
+ dcgdx1_nfeti20h_fc =   0.0000e+00
+ dvth0_nfeti20h_fc =   1.6546e-01
+ dtox_nfeti20h_fc =   0.0000e+00
+ dbeta2_nfeti20h_fc =  -2.6148e-01
+ dvth2_nfeti20h_fc =   2.5809e-01
+ dxw_nfeti20h_fc =   0.0000e+00
+ ddvt0_nfeti20h_fc =   0.0000e+00
+ drj_nfeti20h_fc =   4.5841e-02
+ ddlc_nfeti20h_fc =   0.0000e+00
+ dk2_nfeti20h_fc =   0.0000e+00
+ dxl_nfeti20h_fc =   0.0000e+00
+ duo_nfeti20h_fc =  -1.3976e+01
.endl sf_nfeti20h

.lib fff_nfeti20h
.param
+ dbeta1_nfeti20h_fc =   3.8965e+00
+ dcj_nfeti20h_fc =   0.0000e+00
+ dcgso_nfeti20h_fc =   0.0000e+00
+ dk1_nfeti20h_fc =   0.0000e+00
+ dvth1_nfeti20h_fc =  -2.0987e-01
+ dvsat_nfeti20h_fc =   0.0000e+00
+ dcgdx1_nfeti20h_fc =   0.0000e+00
+ dvth0_nfeti20h_fc =  -2.4228e-01
+ dtox_nfeti20h_fc =  -2.0000e-09
+ dbeta2_nfeti20h_fc =   3.5220e-01
+ dvth2_nfeti20h_fc =  -3.3344e-01
+ dxw_nfeti20h_fc =   3.3333e-07
+ ddvt0_nfeti20h_fc =   1.2000e+00
+ drj_nfeti20h_fc =  -2.9348e-02
+ ddlc_nfeti20h_fc =   0.0000e+00
+ dk2_nfeti20h_fc =   0.0000e+00
+ dxl_nfeti20h_fc =   0.0000e+00
+ duo_nfeti20h_fc =   1.8887e+01
.endl fff_nfeti20h

.lib ssf_nfeti20h
.param
+ dbeta1_nfeti20h_fc =  -2.8639e+00
+ dcj_nfeti20h_fc =   0.0000e+00
+ dcgso_nfeti20h_fc =   0.0000e+00
+ dk1_nfeti20h_fc =   0.0000e+00
+ dvth1_nfeti20h_fc =   2.2756e-01
+ dvsat_nfeti20h_fc =   0.0000e+00
+ dcgdx1_nfeti20h_fc =   0.0000e+00
+ dvth0_nfeti20h_fc =   2.2286e-01
+ dtox_nfeti20h_fc =   2.0000e-09
+ dbeta2_nfeti20h_fc =  -3.5220e-01
+ dvth2_nfeti20h_fc =   3.4763e-01
+ dxw_nfeti20h_fc =  -3.3333e-07
+ ddvt0_nfeti20h_fc =  -1.2000e+00
+ drj_nfeti20h_fc =   6.1745e-02
+ ddlc_nfeti20h_fc =   0.0000e+00
+ dk2_nfeti20h_fc =   0.0000e+00
+ dxl_nfeti20h_fc =   0.0000e+00
+ duo_nfeti20h_fc =  -1.8825e+01
.endl ssf_nfeti20h

.lib tt_pfet20h
.param
+ dbeta1_pfet20h_fc =   0.0000e+00
+ dcj_pfet20h_fc =   0.0000e+00
+ dcgso_pfet20h_fc =   0.0000e+00
+ dk1_pfet20h_fc =   0.0000e+00
+ dvth1_pfet20h_fc =   0.0000e+00
+ dvsat_pfet20h_fc =   0.0000e+00
+ dcgdx1_pfet20h_fc =   0.0000e+00
+ dvth0_pfet20h_fc =   0.0000e+00
+ dtox_pfet20h_fc =   0.0000e+00
+ dbeta2_pfet20h_fc =   0.0000e+00
+ dvth2_pfet20h_fc =   0.0000e+00
+ dxw_pfet20h_fc =   0.0000e+00
+ ddvt0_pfet20h_fc =   0.0000e+00
+ drj_pfet20h_fc =   0.0000e+00
+ ddlc_pfet20h_fc =   0.0000e+00
+ dk2_pfet20h_fc =   0.0000e+00
+ dxl_pfet20h_fc =   0.0000e+00
+ duo_pfet20h_fc =   0.0000e+00
.endl tt_pfet20h

.lib ff_pfet20h
.param
+ dbeta1_pfet20h_fc =   3.0020e-01
+ dcj_pfet20h_fc =   0.0000e+00
+ dcgso_pfet20h_fc =   0.0000e+00
+ dk1_pfet20h_fc =   0.0000e+00
+ dvth1_pfet20h_fc =  -5.6243e-01
+ dvsat_pfet20h_fc =   0.0000e+00
+ dcgdx1_pfet20h_fc =   0.0000e+00
+ dvth0_pfet20h_fc =   2.0684e-01
+ dtox_pfet20h_fc =  -2.0000e-09
+ dbeta2_pfet20h_fc =   2.7808e-02
+ dvth2_pfet20h_fc =  -4.7044e-02
+ dxw_pfet20h_fc =   3.3333e-07
+ ddvt0_pfet20h_fc =   0.0000e+00
+ drj_pfet20h_fc =  -1.1663e-03
+ ddlc_pfet20h_fc =   0.0000e+00
+ dk2_pfet20h_fc =   0.0000e+00
+ dxl_pfet20h_fc =   0.0000e+00
+ duo_pfet20h_fc =   1.1336e+01
.endl ff_pfet20h

.lib ss_pfet20h
.param
+ dbeta1_pfet20h_fc =  -2.7533e-01
+ dcj_pfet20h_fc =   0.0000e+00
+ dcgso_pfet20h_fc =   0.0000e+00
+ dk1_pfet20h_fc =   0.0000e+00
+ dvth1_pfet20h_fc =   4.7961e-01
+ dvsat_pfet20h_fc =   0.0000e+00
+ dcgdx1_pfet20h_fc =   0.0000e+00
+ dvth0_pfet20h_fc =  -1.9059e-01
+ dtox_pfet20h_fc =   2.0000e-09
+ dbeta2_pfet20h_fc =  -5.0843e-02
+ dvth2_pfet20h_fc =   1.2978e-01
+ dxw_pfet20h_fc =  -3.3333e-07
+ ddvt0_pfet20h_fc =  -1.3100e-01
+ drj_pfet20h_fc =   1.8949e-02
+ ddlc_pfet20h_fc =   0.0000e+00
+ dk2_pfet20h_fc =   0.0000e+00
+ dxl_pfet20h_fc =   0.0000e+00
+ duo_pfet20h_fc =  -1.2752e+01
.endl ss_pfet20h

.lib fs_pfet20h
.param
+ dbeta1_pfet20h_fc =  -2.1961e-01
+ dcj_pfet20h_fc =   0.0000e+00
+ dcgso_pfet20h_fc =   0.0000e+00
+ dk1_pfet20h_fc =   0.0000e+00
+ dvth1_pfet20h_fc =   3.8255e-01
+ dvsat_pfet20h_fc =   0.0000e+00
+ dcgdx1_pfet20h_fc =   0.0000e+00
+ dvth0_pfet20h_fc =  -1.5634e-01
+ dtox_pfet20h_fc =   0.0000e+00
+ dbeta2_pfet20h_fc =  -4.0554e-02
+ dvth2_pfet20h_fc =   1.0351e-01
+ dxw_pfet20h_fc =   0.0000e+00
+ ddvt0_pfet20h_fc =   0.0000e+00
+ drj_pfet20h_fc =   1.5114e-02
+ ddlc_pfet20h_fc =   0.0000e+00
+ dk2_pfet20h_fc =   0.0000e+00
+ dxl_pfet20h_fc =   0.0000e+00
+ duo_pfet20h_fc =  -1.0171e+01
.endl fs_pfet20h

.lib sf_pfet20h
.param
+ dbeta1_pfet20h_fc =   2.5626e-01
+ dcj_pfet20h_fc =   0.0000e+00
+ dcgso_pfet20h_fc =   0.0000e+00
+ dk1_pfet20h_fc =   0.0000e+00
+ dvth1_pfet20h_fc =  -4.8011e-01
+ dvsat_pfet20h_fc =   0.0000e+00
+ dcgdx1_pfet20h_fc =   0.0000e+00
+ dvth0_pfet20h_fc =   1.7656e-01
+ dtox_pfet20h_fc =   0.0000e+00
+ dbeta2_pfet20h_fc =   2.3738e-02
+ dvth2_pfet20h_fc =  -4.0158e-02
+ dxw_pfet20h_fc =   0.0000e+00
+ ddvt0_pfet20h_fc =   0.0000e+00
+ drj_pfet20h_fc =  -9.9556e-04
+ ddlc_pfet20h_fc =   0.0000e+00
+ dk2_pfet20h_fc =   0.0000e+00
+ dxl_pfet20h_fc =   0.0000e+00
+ duo_pfet20h_fc =   9.6768e+00
.endl sf_pfet20h

.lib fff_pfet20h
.param
+ dbeta1_pfet20h_fc =   3.0020e-01
+ dcj_pfet20h_fc =   0.0000e+00
+ dcgso_pfet20h_fc =   0.0000e+00
+ dk1_pfet20h_fc =   0.0000e+00
+ dvth1_pfet20h_fc =  -5.6243e-01
+ dvsat_pfet20h_fc =   0.0000e+00
+ dcgdx1_pfet20h_fc =   0.0000e+00
+ dvth0_pfet20h_fc =   2.0684e-01
+ dtox_pfet20h_fc =  -2.0000e-09
+ dbeta2_pfet20h_fc =   2.7808e-02
+ dvth2_pfet20h_fc =  -4.7044e-02
+ dxw_pfet20h_fc =   3.3333e-07
+ ddvt0_pfet20h_fc =   0.0000e+00
+ drj_pfet20h_fc =  -1.1663e-03
+ ddlc_pfet20h_fc =   0.0000e+00
+ dk2_pfet20h_fc =   0.0000e+00
+ dxl_pfet20h_fc =   0.0000e+00
+ duo_pfet20h_fc =   1.1336e+01
.endl fff_pfet20h

.lib ssf_pfet20h
.param
+ dbeta1_pfet20h_fc =  -2.7533e-01
+ dcj_pfet20h_fc =   0.0000e+00
+ dcgso_pfet20h_fc =   0.0000e+00
+ dk1_pfet20h_fc =   0.0000e+00
+ dvth1_pfet20h_fc =   4.7961e-01
+ dvsat_pfet20h_fc =   0.0000e+00
+ dcgdx1_pfet20h_fc =   0.0000e+00
+ dvth0_pfet20h_fc =  -1.9059e-01
+ dtox_pfet20h_fc =   2.0000e-09
+ dbeta2_pfet20h_fc =  -5.0843e-02
+ dvth2_pfet20h_fc =   1.2978e-01
+ dxw_pfet20h_fc =  -3.3333e-07
+ ddvt0_pfet20h_fc =  -1.3100e-01
+ drj_pfet20h_fc =   1.8949e-02
+ ddlc_pfet20h_fc =   0.0000e+00
+ dk2_pfet20h_fc =   0.0000e+00
+ dxl_pfet20h_fc =   0.0000e+00
+ duo_pfet20h_fc =  -1.2752e+01
.endl ssf_pfet20h


.lib tt_nfet20hs
.param
+ dbeta1_nfet20hs_fc =   0.0000e+00
+ dcj_nfet20hs_fc =   0.0000e+00
+ dcgso_nfet20hs_fc =   0.0000e+00
+ dk1_nfet20hs_fc =   0.0000e+00
+ dvth1_nfet20hs_fc =   0.0000e+00
+ dvsat_nfet20hs_fc =   0.0000e+00
+ dcgdx1_nfet20hs_fc =   0.0000e+00
+ dvth0_nfet20hs_fc =   0.0000e+00
+ dtox_nfet20hs_fc =   0.0000e+00
+ dbeta2_nfet20hs_fc =   0.0000e+00
+ dvth2_nfet20hs_fc =   0.0000e+00
+ dxw_nfet20hs_fc =   0.0000e+00
+ ddvt0_nfet20hs_fc =   0.0000e+00
+ drj_nfet20hs_fc =   0.0000e+00
+ ddlc_nfet20hs_fc =   0.0000e+00
+ dk2_nfet20hs_fc =   0.0000e+00
+ dxl_nfet20hs_fc =   0.0000e+00
+ duo_nfet20hs_fc =   0.0000e+00
.endl tt_nfet20hs

.lib ff_nfet20hs
.param
+ dbeta1_nfet20hs_fc =   8.3180e-01
+ dcj_nfet20hs_fc =   0.0000e+00
+ dcgso_nfet20hs_fc =   0.0000e+00
+ dk1_nfet20hs_fc =   0.0000e+00
+ dvth1_nfet20hs_fc =  -1.2343e-02
+ dvsat_nfet20hs_fc =   0.0000e+00
+ dcgdx1_nfet20hs_fc =   0.0000e+00
+ dvth0_nfet20hs_fc =  -1.9720e-01
+ dtox_nfet20hs_fc =  -2.0000e-09
+ dbeta2_nfet20hs_fc =   6.6612e-01
+ dvth2_nfet20hs_fc =  -6.9743e-03
+ dxw_nfet20hs_fc =   3.3333e-07
+ ddvt0_nfet20hs_fc =   0.0000e+00
+ drj_nfet20hs_fc =  -5.5748e-03
+ ddlc_nfet20hs_fc =   0.0000e+00
+ dk2_nfet20hs_fc =   0.0000e+00
+ dxl_nfet20hs_fc =   0.0000e+00
+ duo_nfet20hs_fc =   2.7069e+01
.endl ff_nfet20hs

.lib ss_nfet20hs
.param
+ dbeta1_nfet20hs_fc =  -8.3180e-01
+ dcj_nfet20hs_fc =   0.0000e+00
+ dcgso_nfet20hs_fc =   0.0000e+00
+ dk1_nfet20hs_fc =   0.0000e+00
+ dvth1_nfet20hs_fc =   1.2343e-02
+ dvsat_nfet20hs_fc =   0.0000e+00
+ dcgdx1_nfet20hs_fc =   0.0000e+00
+ dvth0_nfet20hs_fc =   1.9174e-01
+ dtox_nfet20hs_fc =   2.0000e-09
+ dbeta2_nfet20hs_fc =  -6.6614e-01
+ dvth2_nfet20hs_fc =   6.9743e-03
+ dxw_nfet20hs_fc =  -3.3333e-07
+ ddvt0_nfet20hs_fc =   0.0000e+00
+ drj_nfet20hs_fc =   1.5598e-03
+ ddlc_nfet20hs_fc =   0.0000e+00
+ dk2_nfet20hs_fc =   0.0000e+00
+ dxl_nfet20hs_fc =   0.0000e+00
+ duo_nfet20hs_fc =  -2.7444e+01
.endl ss_nfet20hs

.lib fs_nfet20hs
.param
+ dbeta1_nfet20hs_fc =   7.1862e-01
+ dcj_nfet20hs_fc =   0.0000e+00
+ dcgso_nfet20hs_fc =   0.0000e+00
+ dk1_nfet20hs_fc =   0.0000e+00
+ dvth1_nfet20hs_fc =  -1.0664e-02
+ dvsat_nfet20hs_fc =   0.0000e+00
+ dcgdx1_nfet20hs_fc =   0.0000e+00
+ dvth0_nfet20hs_fc =  -1.7037e-01
+ dtox_nfet20hs_fc =   0.0000e+00
+ dbeta2_nfet20hs_fc =   5.7548e-01
+ dvth2_nfet20hs_fc =  -6.0253e-03
+ dxw_nfet20hs_fc =   0.0000e+00
+ ddvt0_nfet20hs_fc =   0.0000e+00
+ drj_nfet20hs_fc =  -4.8163e-03
+ ddlc_nfet20hs_fc =   0.0000e+00
+ dk2_nfet20hs_fc =   0.0000e+00
+ dxl_nfet20hs_fc =   0.0000e+00
+ duo_nfet20hs_fc =   2.3385e+01
.endl fs_nfet20hs

.lib sf_nfet20hs
.param
+ dbeta1_nfet20hs_fc =  -7.6023e-01
+ dcj_nfet20hs_fc =   0.0000e+00
+ dcgso_nfet20hs_fc =   0.0000e+00
+ dk1_nfet20hs_fc =   0.0000e+00
+ dvth1_nfet20hs_fc =   1.1281e-02
+ dvsat_nfet20hs_fc =   0.0000e+00
+ dcgdx1_nfet20hs_fc =   0.0000e+00
+ dvth0_nfet20hs_fc =   1.7524e-01
+ dtox_nfet20hs_fc =   0.0000e+00
+ dbeta2_nfet20hs_fc =  -6.0883e-01
+ dvth2_nfet20hs_fc =   6.3743e-03
+ dxw_nfet20hs_fc =   0.0000e+00
+ ddvt0_nfet20hs_fc =   0.0000e+00
+ drj_nfet20hs_fc =   1.4256e-03
+ ddlc_nfet20hs_fc =   0.0000e+00
+ dk2_nfet20hs_fc =   0.0000e+00
+ dxl_nfet20hs_fc =   0.0000e+00
+ duo_nfet20hs_fc =  -2.5083e+01
.endl sf_nfet20hs

.lib fff_nfet20hs
.param
+ dbeta1_nfet20hs_fc =   8.3180e-01
+ dcj_nfet20hs_fc =   0.0000e+00
+ dcgso_nfet20hs_fc =   0.0000e+00
+ dk1_nfet20hs_fc =   0.0000e+00
+ dvth1_nfet20hs_fc =  -1.2343e-02
+ dvsat_nfet20hs_fc =   0.0000e+00
+ dcgdx1_nfet20hs_fc =   0.0000e+00
+ dvth0_nfet20hs_fc =  -1.9720e-01
+ dtox_nfet20hs_fc =  -2.0000e-09
+ dbeta2_nfet20hs_fc =   6.6612e-01
+ dvth2_nfet20hs_fc =  -6.9743e-03
+ dxw_nfet20hs_fc =   3.3333e-07
+ ddvt0_nfet20hs_fc =   0.0000e+00
+ drj_nfet20hs_fc =  -5.5748e-03
+ ddlc_nfet20hs_fc =   0.0000e+00
+ dk2_nfet20hs_fc =   0.0000e+00
+ dxl_nfet20hs_fc =   0.0000e+00
+ duo_nfet20hs_fc =   2.7069e+01
.endl fff_nfet20hs

.lib ssf_nfet20hs
.param
+ dbeta1_nfet20hs_fc =  -8.3180e-01
+ dcj_nfet20hs_fc =   0.0000e+00
+ dcgso_nfet20hs_fc =   0.0000e+00
+ dk1_nfet20hs_fc =   0.0000e+00
+ dvth1_nfet20hs_fc =   1.2343e-02
+ dvsat_nfet20hs_fc =   0.0000e+00
+ dcgdx1_nfet20hs_fc =   0.0000e+00
+ dvth0_nfet20hs_fc =   1.9174e-01
+ dtox_nfet20hs_fc =   2.0000e-09
+ dbeta2_nfet20hs_fc =  -6.6614e-01
+ dvth2_nfet20hs_fc =   6.9743e-03
+ dxw_nfet20hs_fc =  -3.3333e-07
+ ddvt0_nfet20hs_fc =   0.0000e+00
+ drj_nfet20hs_fc =   1.5598e-03
+ ddlc_nfet20hs_fc =   0.0000e+00
+ dk2_nfet20hs_fc =   0.0000e+00
+ dxl_nfet20hs_fc =   0.0000e+00
+ duo_nfet20hs_fc =  -2.7444e+01
.endl ssf_nfet20hs

.lib tt_pfet20hs
.param
+ dbeta1_pfet20hs_fc =   0.0000e+00
+ dcj_pfet20hs_fc =   0.0000e+00
+ dcgso_pfet20hs_fc =   0.0000e+00
+ dk1_pfet20hs_fc =   0.0000e+00
+ dvth1_pfet20hs_fc =   0.0000e+00
+ dvsat_pfet20hs_fc =   0.0000e+00
+ dcgdx1_pfet20hs_fc =   0.0000e+00
+ dvth0_pfet20hs_fc =   0.0000e+00
+ dtox_pfet20hs_fc =   0.0000e+00
+ dbeta2_pfet20hs_fc =   0.0000e+00
+ dvth2_pfet20hs_fc =   0.0000e+00
+ ddvt0_pfet20hs_fc =   0.0000e+00
+ dxw_pfet20hs_fc =   0.0000e+00
+ drj_pfet20hs_fc =   0.0000e+00
+ ddlc_pfet20hs_fc =   0.0000e+00
+ dk2_pfet20hs_fc =   0.0000e+00
+ dxl_pfet20hs_fc =   0.0000e+00
+ duo_pfet20hs_fc =   0.0000e+00
.endl tt_pfet20hs

.lib ff_pfet20hs
.param
+ dbeta1_pfet20hs_fc =   3.1731e-01
+ dcj_pfet20hs_fc =   0.0000e+00
+ dcgso_pfet20hs_fc =   0.0000e+00
+ dk1_pfet20hs_fc =   0.0000e+00
+ dvth1_pfet20hs_fc =  -1.5680e-01
+ dvsat_pfet20hs_fc =   0.0000e+00
+ dcgdx1_pfet20hs_fc =   0.0000e+00
+ dvth0_pfet20hs_fc =   1.2444e-01
+ dtox_pfet20hs_fc =  -2.0000e-09
+ dbeta2_pfet20hs_fc =   2.7513e-01
+ dvth2_pfet20hs_fc =  -2.4310e+00
+ ddvt0_pfet20hs_fc =   0.0000e+00
+ dxw_pfet20hs_fc =   0.0000e+00
+ drj_pfet20hs_fc =  -1.9039e-02
+ ddlc_pfet20hs_fc =   0.0000e+00
+ dk2_pfet20hs_fc =   0.0000e+00
+ dxl_pfet20hs_fc =   0.0000e+00
+ duo_pfet20hs_fc =   2.4219e+01
.endl ff_pfet20hs

.lib ss_pfet20hs
.param
+ dbeta1_pfet20hs_fc =  -1.6779e-01
+ dcj_pfet20hs_fc =   0.0000e+00
+ dcgso_pfet20hs_fc =   0.0000e+00
+ dk1_pfet20hs_fc =   0.0000e+00
+ dvth1_pfet20hs_fc =   1.9214e-01
+ dvsat_pfet20hs_fc =   0.0000e+00
+ dcgdx1_pfet20hs_fc =   0.0000e+00
+ dvth0_pfet20hs_fc =  -1.1749e-01
+ dtox_pfet20hs_fc =   2.0000e-09
+ dbeta2_pfet20hs_fc =  -2.6515e-01
+ dvth2_pfet20hs_fc =   3.0734e+00
+ ddvt0_pfet20hs_fc =   0.0000e+00
+ dxw_pfet20hs_fc =   0.0000e+00
+ drj_pfet20hs_fc =   2.5644e-02
+ ddlc_pfet20hs_fc =   0.0000e+00
+ dk2_pfet20hs_fc =   0.0000e+00
+ dxl_pfet20hs_fc =   0.0000e+00
+ duo_pfet20hs_fc =  -2.2609e+01
.endl ss_pfet20hs

.lib fs_pfet20hs
.param
+ dbeta1_pfet20hs_fc =  -1.3233e-01
+ dcj_pfet20hs_fc =   0.0000e+00
+ dcgso_pfet20hs_fc =   0.0000e+00
+ dk1_pfet20hs_fc =   0.0000e+00
+ dvth1_pfet20hs_fc =   1.5154e-01
+ dvsat_pfet20hs_fc =   0.0000e+00
+ dcgdx1_pfet20hs_fc =   0.0000e+00
+ dvth0_pfet20hs_fc =  -9.2658e-02
+ dtox_pfet20hs_fc =   0.0000e+00
+ dbeta2_pfet20hs_fc =  -2.0912e-01
+ dvth2_pfet20hs_fc =   2.4239e+00
+ ddvt0_pfet20hs_fc =   0.0000e+00
+ dxw_pfet20hs_fc =   0.0000e+00
+ drj_pfet20hs_fc =   2.0225e-02
+ ddlc_pfet20hs_fc =   0.0000e+00
+ dk2_pfet20hs_fc =   0.0000e+00
+ dxl_pfet20hs_fc =   0.0000e+00
+ duo_pfet20hs_fc =  -1.7831e+01
.endl fs_pfet20hs

.lib sf_pfet20hs
.param
+ dbeta1_pfet20hs_fc =   2.4306e-01
+ dcj_pfet20hs_fc =   0.0000e+00
+ dcgso_pfet20hs_fc =   0.0000e+00
+ dk1_pfet20hs_fc =   0.0000e+00
+ dvth1_pfet20hs_fc =  -1.2011e-01
+ dvsat_pfet20hs_fc =   0.0000e+00
+ dcgdx1_pfet20hs_fc =   0.0000e+00
+ dvth0_pfet20hs_fc =   9.5327e-02
+ dtox_pfet20hs_fc =   0.0000e+00
+ dbeta2_pfet20hs_fc =   2.1076e-01
+ dvth2_pfet20hs_fc =  -1.8622e+00
+ ddvt0_pfet20hs_fc =   0.0000e+00
+ dxw_pfet20hs_fc =   0.0000e+00
+ drj_pfet20hs_fc =  -1.4584e-02
+ ddlc_pfet20hs_fc =   0.0000e+00
+ dk2_pfet20hs_fc =   0.0000e+00
+ dxl_pfet20hs_fc =   0.0000e+00
+ duo_pfet20hs_fc =   1.8552e+01
.endl sf_pfet20hs

.lib fff_pfet20hs
.param
+ dbeta1_pfet20hs_fc =   3.1731e-01
+ dcj_pfet20hs_fc =   0.0000e+00
+ dcgso_pfet20hs_fc =   0.0000e+00
+ dk1_pfet20hs_fc =   0.0000e+00
+ dvth1_pfet20hs_fc =  -1.5680e-01
+ dvsat_pfet20hs_fc =   0.0000e+00
+ dcgdx1_pfet20hs_fc =   0.0000e+00
+ dvth0_pfet20hs_fc =   1.2444e-01
+ dtox_pfet20hs_fc =  -2.0000e-09
+ dbeta2_pfet20hs_fc =   2.7513e-01
+ dvth2_pfet20hs_fc =  -2.4310e+00
+ ddvt0_pfet20hs_fc =   0.0000e+00
+ dxw_pfet20hs_fc =   0.0000e+00
+ drj_pfet20hs_fc =  -1.9039e-02
+ ddlc_pfet20hs_fc =   0.0000e+00
+ dk2_pfet20hs_fc =   0.0000e+00
+ dxl_pfet20hs_fc =   0.0000e+00
+ duo_pfet20hs_fc =   2.4219e+01
.endl fff_pfet20hs

.lib ssf_pfet20hs
.param
+ dbeta1_pfet20hs_fc =  -1.6779e-01
+ dcj_pfet20hs_fc =   0.0000e+00
+ dcgso_pfet20hs_fc =   0.0000e+00
+ dk1_pfet20hs_fc =   0.0000e+00
+ dvth1_pfet20hs_fc =   1.9214e-01
+ dvsat_pfet20hs_fc =   0.0000e+00
+ dcgdx1_pfet20hs_fc =   0.0000e+00
+ dvth0_pfet20hs_fc =  -1.1749e-01
+ dtox_pfet20hs_fc =   2.0000e-09
+ dbeta2_pfet20hs_fc =  -2.6515e-01
+ dvth2_pfet20hs_fc =   3.0734e+00
+ ddvt0_pfet20hs_fc =   0.0000e+00
+ dxw_pfet20hs_fc =   0.0000e+00
+ drj_pfet20hs_fc =   2.5644e-02
+ ddlc_pfet20hs_fc =   0.0000e+00
+ dk2_pfet20hs_fc =   0.0000e+00
+ dxl_pfet20hs_fc =   0.0000e+00
+ duo_pfet20hs_fc =  -2.2609e+01
.endl ssf_pfet20hs


.lib tt_nfeti50h
.param
+ dbeta1_nfeti50h_fc =   0.0000e+00
+ dcj_nfeti50h_fc =   0.0000e+00
+ dcgso_nfeti50h_fc =   0.0000e+00
+ dk1_nfeti50h_fc =   0.0000e+00
+ dvth1_nfeti50h_fc =   0.0000e+00
+ dvsat_nfeti50h_fc =   0.0000e+00
+ dcgdx1_nfeti50h_fc =   0.0000e+00
+ dvth0_nfeti50h_fc =   0.0000e+00
+ dtox_nfeti50h_fc =   0.0000e+00
+ dbeta2_nfeti50h_fc =   0.0000e+00
+ dvth2_nfeti50h_fc =   0.0000e+00
+ dxw_nfeti50h_fc =   0.0000e+00
+ ddvt0_nfeti50h_fc =   0.0000e+00
+ drj_nfeti50h_fc =   0.0000e+00
+ ddlc_nfeti50h_fc =   0.0000e+00
+ dk2_nfeti50h_fc =   0.0000e+00
+ dxl_nfeti50h_fc =   0.0000e+00
+ duo_nfeti50h_fc =   0.0000e+00
.endl tt_nfeti50h

.lib ff_nfeti50h
.param
+ dbeta1_nfeti50h_fc =   6.4684e-01
+ dcj_nfeti50h_fc =   0.0000e+00
+ dcgso_nfeti50h_fc =   0.0000e+00
+ dk1_nfeti50h_fc =   0.0000e+00
+ dvth1_nfeti50h_fc =  -3.6798e-02
+ dvsat_nfeti50h_fc =   0.0000e+00
+ dcgdx1_nfeti50h_fc =   0.0000e+00
+ dvth0_nfeti50h_fc =  -3.3921e-01
+ dtox_nfeti50h_fc =  -2.0000e-09
+ dbeta2_nfeti50h_fc =   1.4472e-01
+ dvth2_nfeti50h_fc =  -2.1600e-02
+ dxw_nfeti50h_fc =   3.3333e-07
+ ddvt0_nfeti50h_fc =   3.1693e+00
+ drj_nfeti50h_fc =  -5.7467e-03
+ ddlc_nfeti50h_fc =   0.0000e+00
+ dk2_nfeti50h_fc =   0.0000e+00
+ dxl_nfeti50h_fc =   0.0000e+00
+ duo_nfeti50h_fc =   2.5998e+01
.endl ff_nfeti50h

.lib ss_nfeti50h
.param
+ dbeta1_nfeti50h_fc =  -5.4658e-01
+ dcj_nfeti50h_fc =   0.0000e+00
+ dcgso_nfeti50h_fc =   0.0000e+00
+ dk1_nfeti50h_fc =   0.0000e+00
+ dvth1_nfeti50h_fc =   1.9880e-01
+ dvsat_nfeti50h_fc =   0.0000e+00
+ dcgdx1_nfeti50h_fc =   0.0000e+00
+ dvth0_nfeti50h_fc =   2.9756e-01
+ dtox_nfeti50h_fc =   2.0000e-09
+ dbeta2_nfeti50h_fc =  -1.1319e-01
+ dvth2_nfeti50h_fc =   6.4800e-01
+ dxw_nfeti50h_fc =  -3.3333e-07
+ ddvt0_nfeti50h_fc =  -4.0000e+00
+ drj_nfeti50h_fc =   5.9076e-03
+ ddlc_nfeti50h_fc =   0.0000e+00
+ dk2_nfeti50h_fc =   0.0000e+00
+ dxl_nfeti50h_fc =   0.0000e+00
+ duo_nfeti50h_fc =  -2.9840e+01
.endl ss_nfeti50h

.lib fs_nfeti50h
.param
+ dbeta1_nfeti50h_fc =   4.7759e-01
+ dcj_nfeti50h_fc =   0.0000e+00
+ dcgso_nfeti50h_fc =   0.0000e+00
+ dk1_nfeti50h_fc =   0.0000e+00
+ dvth1_nfeti50h_fc =  -2.7169e-02
+ dvsat_nfeti50h_fc =   0.0000e+00
+ dcgdx1_nfeti50h_fc =   0.0000e+00
+ dvth0_nfeti50h_fc =  -2.5045e-01
+ dtox_nfeti50h_fc =   0.0000e+00
+ dbeta2_nfeti50h_fc =   1.0685e-01
+ dvth2_nfeti50h_fc =  -1.5948e-02
+ dxw_nfeti50h_fc =   0.0000e+00
+ ddvt0_nfeti50h_fc =   2.3400e+00
+ drj_nfeti50h_fc =  -4.2430e-03
+ ddlc_nfeti50h_fc =   0.0000e+00
+ dk2_nfeti50h_fc =   0.0000e+00
+ dxl_nfeti50h_fc =   0.0000e+00
+ duo_nfeti50h_fc =   1.9196e+01
.endl fs_nfeti50h

.lib sf_nfeti50h
.param
+ dbeta1_nfeti50h_fc =  -4.0138e-01
+ dcj_nfeti50h_fc =   0.0000e+00
+ dcgso_nfeti50h_fc =   0.0000e+00
+ dk1_nfeti50h_fc =   0.0000e+00
+ dvth1_nfeti50h_fc =   1.4599e-01
+ dvsat_nfeti50h_fc =   0.0000e+00
+ dcgdx1_nfeti50h_fc =   0.0000e+00
+ dvth0_nfeti50h_fc =   2.1851e-01
+ dtox_nfeti50h_fc =   0.0000e+00
+ dbeta2_nfeti50h_fc =  -8.3124e-02
+ dvth2_nfeti50h_fc =   4.7586e-01
+ dxw_nfeti50h_fc =   0.0000e+00
+ ddvt0_nfeti50h_fc =  -2.9374e+00
+ drj_nfeti50h_fc =   4.3382e-03
+ ddlc_nfeti50h_fc =   0.0000e+00
+ dk2_nfeti50h_fc =   0.0000e+00
+ dxl_nfeti50h_fc =   0.0000e+00
+ duo_nfeti50h_fc =  -2.1913e+01
.endl sf_nfeti50h

.lib fff_nfeti50h
.param
+ dbeta1_nfeti50h_fc =   6.4684e-01
+ dcj_nfeti50h_fc =   0.0000e+00
+ dcgso_nfeti50h_fc =   0.0000e+00
+ dk1_nfeti50h_fc =   0.0000e+00
+ dvth1_nfeti50h_fc =  -3.6798e-02
+ dvsat_nfeti50h_fc =   0.0000e+00
+ dcgdx1_nfeti50h_fc =   0.0000e+00
+ dvth0_nfeti50h_fc =  -3.3921e-01
+ dtox_nfeti50h_fc =  -2.0000e-09
+ dbeta2_nfeti50h_fc =   1.4472e-01
+ dvth2_nfeti50h_fc =  -2.1600e-02
+ dxw_nfeti50h_fc =   3.3333e-07
+ ddvt0_nfeti50h_fc =   3.1693e+00
+ drj_nfeti50h_fc =  -5.7467e-03
+ ddlc_nfeti50h_fc =   0.0000e+00
+ dk2_nfeti50h_fc =   0.0000e+00
+ dxl_nfeti50h_fc =   0.0000e+00
+ duo_nfeti50h_fc =   2.5998e+01
.endl fff_nfeti50h

.lib ssf_nfeti50h
.param
+ dbeta1_nfeti50h_fc =  -5.4658e-01
+ dcj_nfeti50h_fc =   0.0000e+00
+ dcgso_nfeti50h_fc =   0.0000e+00
+ dk1_nfeti50h_fc =   0.0000e+00
+ dvth1_nfeti50h_fc =   1.9880e-01
+ dvsat_nfeti50h_fc =   0.0000e+00
+ dcgdx1_nfeti50h_fc =   0.0000e+00
+ dvth0_nfeti50h_fc =   2.9756e-01
+ dtox_nfeti50h_fc =   2.0000e-09
+ dbeta2_nfeti50h_fc =  -1.1319e-01
+ dvth2_nfeti50h_fc =   6.4800e-01
+ dxw_nfeti50h_fc =  -3.3333e-07
+ ddvt0_nfeti50h_fc =  -4.0000e+00
+ drj_nfeti50h_fc =   5.9076e-03
+ ddlc_nfeti50h_fc =   0.0000e+00
+ dk2_nfeti50h_fc =   0.0000e+00
+ dxl_nfeti50h_fc =   0.0000e+00
+ duo_nfeti50h_fc =  -2.9840e+01
.endl ssf_nfeti50h

.lib tt_pfet50h
.param
+ dbeta1_pfet50h_fc =   0.0000e+00
+ dcj_pfet50h_fc =   0.0000e+00
+ dcgso_pfet50h_fc =   0.0000e+00
+ dk1_pfet50h_fc =   0.0000e+00
+ dvth1_pfet50h_fc =   0.0000e+00
+ dvsat_pfet50h_fc =   0.0000e+00
+ dcgdx1_pfet50h_fc =   0.0000e+00
+ dvth0_pfet50h_fc =   0.0000e+00
+ dtox_pfet50h_fc =   0.0000e+00
+ dbeta2_pfet50h_fc =   0.0000e+00
+ dvth2_pfet50h_fc =   0.0000e+00
+ dxw_pfet50h_fc =   0.0000e+00
+ ddvt0_pfet50h_fc =   0.0000e+00
+ drj_pfet50h_fc =   0.0000e+00
+ ddlc_pfet50h_fc =   0.0000e+00
+ dk2_pfet50h_fc =   0.0000e+00
+ dxl_pfet50h_fc =   0.0000e+00
+ duo_pfet50h_fc =   0.0000e+00
.endl tt_pfet50h

.lib ff_pfet50h
.param
+ dbeta1_pfet50h_fc =   7.1717e-02
+ dcj_pfet50h_fc =   0.0000e+00
+ dcgso_pfet50h_fc =   0.0000e+00
+ dk1_pfet50h_fc =   0.0000e+00
+ dvth1_pfet50h_fc =  -1.7447e-01
+ dvsat_pfet50h_fc =   0.0000e+00
+ dcgdx1_pfet50h_fc =   0.0000e+00
+ dvth0_pfet50h_fc =   1.7681e-01
+ dtox_pfet50h_fc =  -2.0000e-09
+ dbeta2_pfet50h_fc =   3.0657e-02
+ dvth2_pfet50h_fc =  -4.8859e-01
+ dxw_pfet50h_fc =   3.3333e-07
+ ddvt0_pfet50h_fc =   4.3377e-01
+ drj_pfet50h_fc =  -2.2868e-01
+ ddlc_pfet50h_fc =   0.0000e+00
+ dk2_pfet50h_fc =   0.0000e+00
+ dxl_pfet50h_fc =   0.0000e+00
+ duo_pfet50h_fc =   9.7625e+00
.endl ff_pfet50h

.lib ss_pfet50h
.param
+ dbeta1_pfet50h_fc =  -6.6721e-02
+ dcj_pfet50h_fc =   0.0000e+00
+ dcgso_pfet50h_fc =   0.0000e+00
+ dk1_pfet50h_fc =   0.0000e+00
+ dvth1_pfet50h_fc =   2.9822e-01
+ dvsat_pfet50h_fc =   0.0000e+00
+ dcgdx1_pfet50h_fc =   0.0000e+00
+ dvth0_pfet50h_fc =  -1.8709e-01
+ dtox_pfet50h_fc =   2.0000e-09
+ dbeta2_pfet50h_fc =  -2.2312e-02
+ dvth2_pfet50h_fc =   9.9835e-01
+ dxw_pfet50h_fc =  -3.3333e-07
+ ddvt0_pfet50h_fc =  -3.4702e-01
+ drj_pfet50h_fc =   3.5675e-01
+ ddlc_pfet50h_fc =   0.0000e+00
+ dk2_pfet50h_fc =   0.0000e+00
+ dxl_pfet50h_fc =   0.0000e+00
+ duo_pfet50h_fc =  -1.0490e+01
.endl ss_pfet50h

.lib fs_pfet50h
.param
+ dbeta1_pfet50h_fc =  -5.4019e-02
+ dcj_pfet50h_fc =   0.0000e+00
+ dcgso_pfet50h_fc =   0.0000e+00
+ dk1_pfet50h_fc =   0.0000e+00
+ dvth1_pfet50h_fc =   2.4145e-01
+ dvsat_pfet50h_fc =   0.0000e+00
+ dcgdx1_pfet50h_fc =   0.0000e+00
+ dvth0_pfet50h_fc =  -1.5148e-01
+ dtox_pfet50h_fc =   0.0000e+00
+ dbeta2_pfet50h_fc =  -1.8064e-02
+ dvth2_pfet50h_fc =   8.0830e-01
+ dxw_pfet50h_fc =   0.0000e+00
+ ddvt0_pfet50h_fc =  -2.8096e-01
+ drj_pfet50h_fc =   2.8884e-01
+ ddlc_pfet50h_fc =   0.0000e+00
+ dk2_pfet50h_fc =   0.0000e+00
+ dxl_pfet50h_fc =   0.0000e+00
+ duo_pfet50h_fc =  -8.4931e+00
.endl fs_pfet50h

.lib sf_pfet50h
.param
+ dbeta1_pfet50h_fc =   6.3264e-02
+ dcj_pfet50h_fc =   0.0000e+00
+ dcgso_pfet50h_fc =   0.0000e+00
+ dk1_pfet50h_fc =   0.0000e+00
+ dvth1_pfet50h_fc =  -1.5391e-01
+ dvsat_pfet50h_fc =   0.0000e+00
+ dcgdx1_pfet50h_fc =   0.0000e+00
+ dvth0_pfet50h_fc =   1.5597e-01
+ dtox_pfet50h_fc =   0.0000e+00
+ dbeta2_pfet50h_fc =   2.7044e-02
+ dvth2_pfet50h_fc =  -4.3100e-01
+ dxw_pfet50h_fc =   0.0000e+00
+ ddvt0_pfet50h_fc =   3.8265e-01
+ drj_pfet50h_fc =  -2.0173e-01
+ ddlc_pfet50h_fc =   0.0000e+00
+ dk2_pfet50h_fc =   0.0000e+00
+ dxl_pfet50h_fc =   0.0000e+00
+ duo_pfet50h_fc =   8.6119e+00
.endl sf_pfet50h

.lib fff_pfet50h
.param
+ dbeta1_pfet50h_fc =   7.1717e-02
+ dcj_pfet50h_fc =   0.0000e+00
+ dcgso_pfet50h_fc =   0.0000e+00
+ dk1_pfet50h_fc =   0.0000e+00
+ dvth1_pfet50h_fc =  -1.7447e-01
+ dvsat_pfet50h_fc =   0.0000e+00
+ dcgdx1_pfet50h_fc =   0.0000e+00
+ dvth0_pfet50h_fc =   1.7681e-01
+ dtox_pfet50h_fc =  -2.0000e-09
+ dbeta2_pfet50h_fc =   3.0657e-02
+ dvth2_pfet50h_fc =  -4.8859e-01
+ dxw_pfet50h_fc =   3.3333e-07
+ ddvt0_pfet50h_fc =   4.3377e-01
+ drj_pfet50h_fc =  -2.2868e-01
+ ddlc_pfet50h_fc =   0.0000e+00
+ dk2_pfet50h_fc =   0.0000e+00
+ dxl_pfet50h_fc =   0.0000e+00
+ duo_pfet50h_fc =   9.7625e+00
.endl fff_pfet50h

.lib ssf_pfet50h
.param
+ dbeta1_pfet50h_fc =  -6.6721e-02
+ dcj_pfet50h_fc =   0.0000e+00
+ dcgso_pfet50h_fc =   0.0000e+00
+ dk1_pfet50h_fc =   0.0000e+00
+ dvth1_pfet50h_fc =   2.9822e-01
+ dvsat_pfet50h_fc =   0.0000e+00
+ dcgdx1_pfet50h_fc =   0.0000e+00
+ dvth0_pfet50h_fc =  -1.8709e-01
+ dtox_pfet50h_fc =   2.0000e-09
+ dbeta2_pfet50h_fc =  -2.2312e-02
+ dvth2_pfet50h_fc =   9.9835e-01
+ dxw_pfet50h_fc =  -3.3333e-07
+ ddvt0_pfet50h_fc =  -3.4702e-01
+ drj_pfet50h_fc =   3.5675e-01
+ ddlc_pfet50h_fc =   0.0000e+00
+ dk2_pfet50h_fc =   0.0000e+00
+ dxl_pfet50h_fc =   0.0000e+00
+ duo_pfet50h_fc =  -1.0490e+01
.endl ssf_pfet50h


.lib tt_nfet50hs
.param
+ dbeta1_nfet50hs_fc =   0.0000e+00
+ dcj_nfet50hs_fc =   0.0000e+00
+ dcgso_nfet50hs_fc =   0.0000e+00
+ dk1_nfet50hs_fc =   0.0000e+00
+ dvth1_nfet50hs_fc =   0.0000e+00
+ dvsat_nfet50hs_fc =   0.0000e+00
+ dcgdx1_nfet50hs_fc =   0.0000e+00
+ dvth0_nfet50hs_fc =   0.0000e+00
+ dtox_nfet50hs_fc =   0.0000e+00
+ dbeta2_nfet50hs_fc =   0.0000e+00
+ dvth2_nfet50hs_fc =   0.0000e+00
+ dxw_nfet50hs_fc =   0.0000e+00
+ ddvt0_nfet50hs_fc =   0.0000e+00
+ drj_nfet50hs_fc =   0.0000e+00
+ ddlc_nfet50hs_fc =   0.0000e+00
+ dk2_nfet50hs_fc =   0.0000e+00
+ dxl_nfet50hs_fc =   0.0000e+00
+ duo_nfet50hs_fc =   0.0000e+00
.endl tt_nfet50hs

.lib ff_nfet50hs
.param
+ dbeta1_nfet50hs_fc =   1.0141e-01
+ dcj_nfet50hs_fc =   0.0000e+00
+ dcgso_nfet50hs_fc =   0.0000e+00
+ dk1_nfet50hs_fc =   0.0000e+00
+ dvth1_nfet50hs_fc =  -2.1126e-01
+ dvsat_nfet50hs_fc =   0.0000e+00
+ dcgdx1_nfet50hs_fc =   0.0000e+00
+ dvth0_nfet50hs_fc =  -1.6892e-01
+ dtox_nfet50hs_fc =  -2.0000e-09
+ dbeta2_nfet50hs_fc =   1.5056e-01
+ dvth2_nfet50hs_fc =  -3.6975e-01
+ dxw_nfet50hs_fc =   3.3333e-07
+ ddvt0_nfet50hs_fc =   0.0000e+00
+ drj_nfet50hs_fc =  -1.7278e-03
+ ddlc_nfet50hs_fc =   0.0000e+00
+ dk2_nfet50hs_fc =   0.0000e+00
+ dxl_nfet50hs_fc =   0.0000e+00
+ duo_nfet50hs_fc =   2.7556e+01
.endl ff_nfet50hs

.lib ss_nfet50hs
.param
+ dbeta1_nfet50hs_fc =  -1.0141e-01
+ dcj_nfet50hs_fc =   0.0000e+00
+ dcgso_nfet50hs_fc =   0.0000e+00
+ dk1_nfet50hs_fc =   0.0000e+00
+ dvth1_nfet50hs_fc =   1.4000e-02
+ dvsat_nfet50hs_fc =   0.0000e+00
+ dcgdx1_nfet50hs_fc =   0.0000e+00
+ dvth0_nfet50hs_fc =   1.6273e-01
+ dtox_nfet50hs_fc =   2.0000e-09
+ dbeta2_nfet50hs_fc =  -1.5056e-01
+ dvth2_nfet50hs_fc =   2.4650e-02
+ dxw_nfet50hs_fc =  -3.3333e-07
+ ddvt0_nfet50hs_fc =   0.0000e+00
+ drj_nfet50hs_fc =   1.7278e-03
+ ddlc_nfet50hs_fc =   0.0000e+00
+ dk2_nfet50hs_fc =   0.0000e+00
+ dxl_nfet50hs_fc =   0.0000e+00
+ duo_nfet50hs_fc =  -3.1730e+01
.endl ss_nfet50hs

.lib fs_nfet50hs
.param
+ dbeta1_nfet50hs_fc =   8.7896e-02
+ dcj_nfet50hs_fc =   0.0000e+00
+ dcgso_nfet50hs_fc =   0.0000e+00
+ dk1_nfet50hs_fc =   0.0000e+00
+ dvth1_nfet50hs_fc =  -1.8311e-01
+ dvsat_nfet50hs_fc =   0.0000e+00
+ dcgdx1_nfet50hs_fc =   0.0000e+00
+ dvth0_nfet50hs_fc =  -1.4641e-01
+ dtox_nfet50hs_fc =   0.0000e+00
+ dbeta2_nfet50hs_fc =   1.3050e-01
+ dvth2_nfet50hs_fc =  -3.2048e-01
+ dxw_nfet50hs_fc =   0.0000e+00
+ ddvt0_nfet50hs_fc =   0.0000e+00
+ drj_nfet50hs_fc =  -1.4976e-03
+ ddlc_nfet50hs_fc =   0.0000e+00
+ dk2_nfet50hs_fc =   0.0000e+00
+ dxl_nfet50hs_fc =   0.0000e+00
+ duo_nfet50hs_fc =   2.3884e+01
.endl fs_nfet50hs

.lib sf_nfet50hs
.param
+ dbeta1_nfet50hs_fc =  -8.9481e-02
+ dcj_nfet50hs_fc =   0.0000e+00
+ dcgso_nfet50hs_fc =   0.0000e+00
+ dk1_nfet50hs_fc =   0.0000e+00
+ dvth1_nfet50hs_fc =   1.2353e-02
+ dvsat_nfet50hs_fc =   0.0000e+00
+ dcgdx1_nfet50hs_fc =   0.0000e+00
+ dvth0_nfet50hs_fc =   1.4359e-01
+ dtox_nfet50hs_fc =   0.0000e+00
+ dbeta2_nfet50hs_fc =  -1.3285e-01
+ dvth2_nfet50hs_fc =   2.1750e-02
+ dxw_nfet50hs_fc =   0.0000e+00
+ ddvt0_nfet50hs_fc =   0.0000e+00
+ drj_nfet50hs_fc =   1.5246e-03
+ ddlc_nfet50hs_fc =   0.0000e+00
+ dk2_nfet50hs_fc =   0.0000e+00
+ dxl_nfet50hs_fc =   0.0000e+00
+ duo_nfet50hs_fc =  -2.7997e+01
.endl sf_nfet50hs

.lib fff_nfet50hs
.param
+ dbeta1_nfet50hs_fc =   1.0141e-01
+ dcj_nfet50hs_fc =   0.0000e+00
+ dcgso_nfet50hs_fc =   0.0000e+00
+ dk1_nfet50hs_fc =   0.0000e+00
+ dvth1_nfet50hs_fc =  -2.1126e-01
+ dvsat_nfet50hs_fc =   0.0000e+00
+ dcgdx1_nfet50hs_fc =   0.0000e+00
+ dvth0_nfet50hs_fc =  -1.6892e-01
+ dtox_nfet50hs_fc =  -2.0000e-09
+ dbeta2_nfet50hs_fc =   1.5056e-01
+ dvth2_nfet50hs_fc =  -3.6975e-01
+ dxw_nfet50hs_fc =   3.3333e-07
+ ddvt0_nfet50hs_fc =   0.0000e+00
+ drj_nfet50hs_fc =  -1.7278e-03
+ ddlc_nfet50hs_fc =   0.0000e+00
+ dk2_nfet50hs_fc =   0.0000e+00
+ dxl_nfet50hs_fc =   0.0000e+00
+ duo_nfet50hs_fc =   2.7556e+01
.endl fff_nfet50hs

.lib ssf_nfet50hs
.param
+ dbeta1_nfet50hs_fc =  -1.0141e-01
+ dcj_nfet50hs_fc =   0.0000e+00
+ dcgso_nfet50hs_fc =   0.0000e+00
+ dk1_nfet50hs_fc =   0.0000e+00
+ dvth1_nfet50hs_fc =   1.4000e-02
+ dvsat_nfet50hs_fc =   0.0000e+00
+ dcgdx1_nfet50hs_fc =   0.0000e+00
+ dvth0_nfet50hs_fc =   1.6273e-01
+ dtox_nfet50hs_fc =   2.0000e-09
+ dbeta2_nfet50hs_fc =  -1.5056e-01
+ dvth2_nfet50hs_fc =   2.4650e-02
+ dxw_nfet50hs_fc =  -3.3333e-07
+ ddvt0_nfet50hs_fc =   0.0000e+00
+ drj_nfet50hs_fc =   1.7278e-03
+ ddlc_nfet50hs_fc =   0.0000e+00
+ dk2_nfet50hs_fc =   0.0000e+00
+ dxl_nfet50hs_fc =   0.0000e+00
+ duo_nfet50hs_fc =  -3.1730e+01
.endl ssf_nfet50hs

.lib tt_pfet50hs
.param
+ dbeta1_pfet50hs_fc =   0.0000e+00
+ dcj_pfet50hs_fc =   0.0000e+00
+ dcgso_pfet50hs_fc =   0.0000e+00
+ dk1_pfet50hs_fc =   0.0000e+00
+ dvth1_pfet50hs_fc =   0.0000e+00
+ dvsat_pfet50hs_fc =   0.0000e+00
+ dcgdx1_pfet50hs_fc =   0.0000e+00
+ dvth0_pfet50hs_fc =   0.0000e+00
+ dtox_pfet50hs_fc =   0.0000e+00
+ dbeta2_pfet50hs_fc =   0.0000e+00
+ dvth2_pfet50hs_fc =   0.0000e+00
+ ddvt0_pfet50hs_fc =   0.0000e+00
+ dxw_pfet50hs_fc =   0.0000e+00
+ drj_pfet50hs_fc =   0.0000e+00
+ ddlc_pfet50hs_fc =   0.0000e+00
+ dk2_pfet50hs_fc =   0.0000e+00
+ dxl_pfet50hs_fc =   0.0000e+00
+ duo_pfet50hs_fc =   0.0000e+00
.endl tt_pfet50hs

.lib ff_pfet50hs
.param
+ dbeta1_pfet50hs_fc =   1.6594e-01
+ dcj_pfet50hs_fc =   0.0000e+00
+ dcgso_pfet50hs_fc =   0.0000e+00
+ dk1_pfet50hs_fc =   0.0000e+00
+ dvth1_pfet50hs_fc =  -2.6300e-01
+ dvsat_pfet50hs_fc =   0.0000e+00
+ dcgdx1_pfet50hs_fc =   0.0000e+00
+ dvth0_pfet50hs_fc =   1.0679e-01
+ dtox_pfet50hs_fc =  -2.0000e-09
+ dbeta2_pfet50hs_fc =   1.5879e-02
+ dvth2_pfet50hs_fc =  -2.5427e-02
+ ddvt0_pfet50hs_fc =   0.0000e+00
+ dxw_pfet50hs_fc =   0.0000e+00
+ drj_pfet50hs_fc =  -3.7203e-02
+ ddlc_pfet50hs_fc =   0.0000e+00
+ dk2_pfet50hs_fc =   0.0000e+00
+ dxl_pfet50hs_fc =   0.0000e+00
+ duo_pfet50hs_fc =   2.1929e+01
.endl ff_pfet50hs

.lib ss_pfet50hs
.param
+ dbeta1_pfet50hs_fc =  -1.1802e-01
+ dcj_pfet50hs_fc =   0.0000e+00
+ dcgso_pfet50hs_fc =   0.0000e+00
+ dk1_pfet50hs_fc =   0.0000e+00
+ dvth1_pfet50hs_fc =   2.2481e-01
+ dvsat_pfet50hs_fc =   0.0000e+00
+ dcgdx1_pfet50hs_fc =   0.0000e+00
+ dvth0_pfet50hs_fc =  -1.0716e-01
+ dtox_pfet50hs_fc =   2.0000e-09
+ dbeta2_pfet50hs_fc =  -2.0004e-02
+ dvth2_pfet50hs_fc =   1.9833e-01
+ ddvt0_pfet50hs_fc =   0.0000e+00
+ dxw_pfet50hs_fc =   0.0000e+00
+ drj_pfet50hs_fc =   6.6296e-01
+ ddlc_pfet50hs_fc =   0.0000e+00
+ dk2_pfet50hs_fc =   0.0000e+00
+ dxl_pfet50hs_fc =   0.0000e+00
+ duo_pfet50hs_fc =  -2.2859e+01
.endl ss_pfet50hs

.lib fs_pfet50hs
.param
+ dbeta1_pfet50hs_fc =  -9.1419e-02
+ dcj_pfet50hs_fc =   0.0000e+00
+ dcgso_pfet50hs_fc =   0.0000e+00
+ dk1_pfet50hs_fc =   0.0000e+00
+ dvth1_pfet50hs_fc =   1.7414e-01
+ dvsat_pfet50hs_fc =   0.0000e+00
+ dcgdx1_pfet50hs_fc =   0.0000e+00
+ dvth0_pfet50hs_fc =  -8.3009e-02
+ dtox_pfet50hs_fc =   0.0000e+00
+ dbeta2_pfet50hs_fc =  -1.5495e-02
+ dvth2_pfet50hs_fc =   1.5363e-01
+ ddvt0_pfet50hs_fc =   0.0000e+00
+ dxw_pfet50hs_fc =   0.0000e+00
+ drj_pfet50hs_fc =   5.1354e-01
+ ddlc_pfet50hs_fc =   0.0000e+00
+ dk2_pfet50hs_fc =   0.0000e+00
+ dxl_pfet50hs_fc =   0.0000e+00
+ duo_pfet50hs_fc =  -1.7707e+01
.endl fs_pfet50hs

.lib sf_pfet50hs
.param
+ dbeta1_pfet50hs_fc =   1.2962e-01
+ dcj_pfet50hs_fc =   0.0000e+00
+ dcgso_pfet50hs_fc =   0.0000e+00
+ dk1_pfet50hs_fc =   0.0000e+00
+ dvth1_pfet50hs_fc =  -2.0544e-01
+ dvsat_pfet50hs_fc =   0.0000e+00
+ dcgdx1_pfet50hs_fc =   0.0000e+00
+ dvth0_pfet50hs_fc =   8.3417e-02
+ dtox_pfet50hs_fc =   0.0000e+00
+ dbeta2_pfet50hs_fc =   1.2403e-02
+ dvth2_pfet50hs_fc =  -1.9861e-02
+ ddvt0_pfet50hs_fc =   0.0000e+00
+ dxw_pfet50hs_fc =   0.0000e+00
+ drj_pfet50hs_fc =  -2.9060e-02
+ ddlc_pfet50hs_fc =   0.0000e+00
+ dk2_pfet50hs_fc =   0.0000e+00
+ dxl_pfet50hs_fc =   0.0000e+00
+ duo_pfet50hs_fc =   1.7129e+01
.endl sf_pfet50hs

.lib fff_pfet50hs
.param
+ dbeta1_pfet50hs_fc =   1.6594e-01
+ dcj_pfet50hs_fc =   0.0000e+00
+ dcgso_pfet50hs_fc =   0.0000e+00
+ dk1_pfet50hs_fc =   0.0000e+00
+ dvth1_pfet50hs_fc =  -2.6300e-01
+ dvsat_pfet50hs_fc =   0.0000e+00
+ dcgdx1_pfet50hs_fc =   0.0000e+00
+ dvth0_pfet50hs_fc =   1.0679e-01
+ dtox_pfet50hs_fc =  -2.0000e-09
+ dbeta2_pfet50hs_fc =   1.5879e-02
+ dvth2_pfet50hs_fc =  -2.5427e-02
+ ddvt0_pfet50hs_fc =   0.0000e+00
+ dxw_pfet50hs_fc =   0.0000e+00
+ drj_pfet50hs_fc =  -3.7203e-02
+ ddlc_pfet50hs_fc =   0.0000e+00
+ dk2_pfet50hs_fc =   0.0000e+00
+ dxl_pfet50hs_fc =   0.0000e+00
+ duo_pfet50hs_fc =   2.1929e+01
.endl fff_pfet50hs

.lib ssf_pfet50hs
.param
+ dbeta1_pfet50hs_fc =  -1.1802e-01
+ dcj_pfet50hs_fc =   0.0000e+00
+ dcgso_pfet50hs_fc =   0.0000e+00
+ dk1_pfet50hs_fc =   0.0000e+00
+ dvth1_pfet50hs_fc =   2.2481e-01
+ dvsat_pfet50hs_fc =   0.0000e+00
+ dcgdx1_pfet50hs_fc =   0.0000e+00
+ dvth0_pfet50hs_fc =  -1.0716e-01
+ dtox_pfet50hs_fc =   2.0000e-09
+ dbeta2_pfet50hs_fc =  -2.0004e-02
+ dvth2_pfet50hs_fc =   1.9833e-01
+ ddvt0_pfet50hs_fc =   0.0000e+00
+ dxw_pfet50hs_fc =   0.0000e+00
+ drj_pfet50hs_fc =   6.6296e-01
+ ddlc_pfet50hs_fc =   0.0000e+00
+ dk2_pfet50hs_fc =   0.0000e+00
+ dxl_pfet50hs_fc =   0.0000e+00
+ duo_pfet50hs_fc =  -2.2859e+01
.endl ssf_pfet50hs


.lib tt_nfet12mh
.param
+ dsc3_nfet12mh_fc =   0.0000e+00
+ dcj_nfet12mh_fc =   0.0000e+00
+ dcgso_nfet12mh_fc =   0.0000e+00
+ dvfbc_nfet12mh_fc =   0.0000e+00
+ dcgdo_nfet12mh_fc =   0.0000e+00
+ dloverld_nfet12mh_fc =   0.0000e+00
+ dsc2_nfet12mh_fc =   0.0000e+00
+ dxld_nfet12mh_fc =   0.0000e+00
+ dsc1_nfet12mh_fc =   0.0000e+00
+ dvmax_nfet12mh_fc =   0.0000e+00
+ dmueph1_nfet12mh_fc =   0.0000e+00
+ dxldld_nfet12mh_fc =   0.0000e+00
+ dtox_nfet12mh_fc =   0.0000e+00
+ dnsubc_nfet12mh_fc =   0.0000e+00
+ drd_nfet12mh_fc =   0.0000e+00
.endl tt_nfet12mh

.lib ff_nfet12mh
.param
+ dsc3_nfet12mh_fc =   5.7202e-08
+ dcj_nfet12mh_fc =   0.0000e+00
+ dcgso_nfet12mh_fc =  -1.3333e-12
+ dvfbc_nfet12mh_fc =  -2.0000e-02
+ dcgdo_nfet12mh_fc =  -8.0000e-12
+ dloverld_nfet12mh_fc =   0.0000e+00
+ dsc2_nfet12mh_fc =  -2.2200e-16
+ dxld_nfet12mh_fc =   0.0000e+00
+ dsc1_nfet12mh_fc =   9.2220e+00
+ dvmax_nfet12mh_fc =   7.2167e+05
+ dmueph1_nfet12mh_fc =   4.3960e+02
+ dxldld_nfet12mh_fc =   0.0000e+00
+ dtox_nfet12mh_fc =  -4.0000e-10
+ dnsubc_nfet12mh_fc =  -1.4409e+16
+ drd_nfet12mh_fc =  -1.0000e-04
.endl ff_nfet12mh

.lib ss_nfet12mh
.param
+ dsc3_nfet12mh_fc =  -7.4450e-08
+ dcj_nfet12mh_fc =   0.0000e+00
+ dcgso_nfet12mh_fc =   1.3333e-12
+ dvfbc_nfet12mh_fc =   2.0000e-02
+ dcgdo_nfet12mh_fc =   8.0000e-12
+ dloverld_nfet12mh_fc =   0.0000e+00
+ dsc2_nfet12mh_fc =   2.2200e-16
+ dxld_nfet12mh_fc =   0.0000e+00
+ dsc1_nfet12mh_fc =  -7.1820e+00
+ dvmax_nfet12mh_fc =  -7.1167e+05
+ dmueph1_nfet12mh_fc =  -4.4200e+02
+ dxldld_nfet12mh_fc =   0.0000e+00
+ dtox_nfet12mh_fc =   4.0000e-10
+ dnsubc_nfet12mh_fc =   1.4937e+16
+ drd_nfet12mh_fc =   1.0000e-04
.endl ss_nfet12mh

.lib fs_nfet12mh
.param
+ dsc3_nfet12mh_fc =   4.1688e-08
+ dcj_nfet12mh_fc =   0.0000e+00
+ dcgso_nfet12mh_fc =   0.0000e+00
+ dvfbc_nfet12mh_fc =  -1.4576e-02
+ dcgdo_nfet12mh_fc =   0.0000e+00
+ dloverld_nfet12mh_fc =   0.0000e+00
+ dsc2_nfet12mh_fc =  -1.6179e-16
+ dxld_nfet12mh_fc =   0.0000e+00
+ dsc1_nfet12mh_fc =   6.7208e+00
+ dvmax_nfet12mh_fc =   5.2594e+05
+ dmueph1_nfet12mh_fc =   3.2037e+02
+ dxldld_nfet12mh_fc =   0.0000e+00
+ dtox_nfet12mh_fc =   0.0000e+00
+ dnsubc_nfet12mh_fc =  -1.0501e+16
+ drd_nfet12mh_fc =  -7.2878e-05
.endl fs_nfet12mh

.lib sf_nfet12mh
.param
+ dsc3_nfet12mh_fc =  -5.5066e-08
+ dcj_nfet12mh_fc =   0.0000e+00
+ dcgso_nfet12mh_fc =   0.0000e+00
+ dvfbc_nfet12mh_fc =   1.4793e-02
+ dcgdo_nfet12mh_fc =   0.0000e+00
+ dloverld_nfet12mh_fc =   0.0000e+00
+ dsc2_nfet12mh_fc =   1.6420e-16
+ dxld_nfet12mh_fc =   0.0000e+00
+ dsc1_nfet12mh_fc =  -5.3121e+00
+ dvmax_nfet12mh_fc =  -5.2638e+05
+ dmueph1_nfet12mh_fc =  -3.2692e+02
+ dxldld_nfet12mh_fc =   0.0000e+00
+ dtox_nfet12mh_fc =   0.0000e+00
+ dnsubc_nfet12mh_fc =   1.1048e+16
+ drd_nfet12mh_fc =   7.3964e-05
.endl sf_nfet12mh

.lib fff_nfet12mh
.param
+ dsc3_nfet12mh_fc =   5.7202e-08
+ dcj_nfet12mh_fc =   0.0000e+00
+ dcgso_nfet12mh_fc =  -1.3333e-12
+ dvfbc_nfet12mh_fc =  -2.0000e-02
+ dcgdo_nfet12mh_fc =  -8.0000e-12
+ dloverld_nfet12mh_fc =   0.0000e+00
+ dsc2_nfet12mh_fc =  -2.2200e-16
+ dxld_nfet12mh_fc =   0.0000e+00
+ dsc1_nfet12mh_fc =   9.2220e+00
+ dvmax_nfet12mh_fc =   7.2167e+05
+ dmueph1_nfet12mh_fc =   4.3960e+02
+ dxldld_nfet12mh_fc =   0.0000e+00
+ dtox_nfet12mh_fc =  -4.0000e-10
+ dnsubc_nfet12mh_fc =  -1.4409e+16
+ drd_nfet12mh_fc =  -1.0000e-04
.endl fff_nfet12mh

.lib ssf_nfet12mh
.param
+ dsc3_nfet12mh_fc =  -7.4450e-08
+ dcj_nfet12mh_fc =   0.0000e+00
+ dcgso_nfet12mh_fc =   1.3333e-12
+ dvfbc_nfet12mh_fc =   2.0000e-02
+ dcgdo_nfet12mh_fc =   8.0000e-12
+ dloverld_nfet12mh_fc =   0.0000e+00
+ dsc2_nfet12mh_fc =   2.2200e-16
+ dxld_nfet12mh_fc =   0.0000e+00
+ dsc1_nfet12mh_fc =  -7.1820e+00
+ dvmax_nfet12mh_fc =  -7.1167e+05
+ dmueph1_nfet12mh_fc =  -4.4200e+02
+ dxldld_nfet12mh_fc =   0.0000e+00
+ dtox_nfet12mh_fc =   4.0000e-10
+ dnsubc_nfet12mh_fc =   1.4937e+16
+ drd_nfet12mh_fc =   1.0000e-04
.endl ssf_nfet12mh

.lib tt_pfet12mh
.param
+ dsc3_pfet12mh_fc =   0.0000e+00
+ dcj_pfet12mh_fc =   0.0000e+00
+ dcgso_pfet12mh_fc =   0.0000e+00
+ dvfbc_pfet12mh_fc =   0.0000e+00
+ dcgdo_pfet12mh_fc =   0.0000e+00
+ dloverld_pfet12mh_fc =   0.0000e+00
+ dsc2_pfet12mh_fc =   0.0000e+00
+ dxld_pfet12mh_fc =   0.0000e+00
+ dsc1_pfet12mh_fc =   0.0000e+00
+ dvmax_pfet12mh_fc =   0.0000e+00
+ dmueph1_pfet12mh_fc =   0.0000e+00
+ dxldld_pfet12mh_fc =   0.0000e+00
+ dtox_pfet12mh_fc =   0.0000e+00
+ dnsubc_pfet12mh_fc =   0.0000e+00
+ drd_pfet12mh_fc =   0.0000e+00
.endl tt_pfet12mh

.lib ff_pfet12mh
.param
+ dsc3_pfet12mh_fc =   0.0000e+00
+ dcj_pfet12mh_fc =   0.0000e+00
+ dcgso_pfet12mh_fc =  -6.6667e-13
+ dvfbc_pfet12mh_fc =  -3.7332e-02
+ dcgdo_pfet12mh_fc =  -6.6667e-12
+ dloverld_pfet12mh_fc =   0.0000e+00
+ dsc2_pfet12mh_fc =   2.0000e-03
+ dxld_pfet12mh_fc =   0.0000e+00
+ dsc1_pfet12mh_fc =   0.0000e+00
+ dvmax_pfet12mh_fc =   1.9400e+04
+ dmueph1_pfet12mh_fc =   0.0000e+00
+ dxldld_pfet12mh_fc =   0.0000e+00
+ dtox_pfet12mh_fc =  -4.0000e-10
+ dnsubc_pfet12mh_fc =  -9.0629e+15
+ drd_pfet12mh_fc =  -1.1431e-03
.endl ff_pfet12mh

.lib ss_pfet12mh
.param
+ dsc3_pfet12mh_fc =   0.0000e+00
+ dcj_pfet12mh_fc =   0.0000e+00
+ dcgso_pfet12mh_fc =   6.6667e-13
+ dvfbc_pfet12mh_fc =   4.6683e-02
+ dcgdo_pfet12mh_fc =   6.6667e-12
+ dloverld_pfet12mh_fc =   0.0000e+00
+ dsc2_pfet12mh_fc =  -2.0000e-03
+ dxld_pfet12mh_fc =   0.0000e+00
+ dsc1_pfet12mh_fc =   0.0000e+00
+ dvmax_pfet12mh_fc =  -1.9400e+04
+ dmueph1_pfet12mh_fc =   0.0000e+00
+ dxldld_pfet12mh_fc =   0.0000e+00
+ dtox_pfet12mh_fc =   4.0000e-10
+ dnsubc_pfet12mh_fc =   6.9055e+15
+ drd_pfet12mh_fc =   1.2513e-03
.endl ss_pfet12mh

.lib fs_pfet12mh
.param
+ dsc3_pfet12mh_fc =   0.0000e+00
+ dcj_pfet12mh_fc =   0.0000e+00
+ dcgso_pfet12mh_fc =   0.0000e+00
+ dvfbc_pfet12mh_fc =   3.2188e-02
+ dcgdo_pfet12mh_fc =   0.0000e+00
+ dloverld_pfet12mh_fc =   0.0000e+00
+ dsc2_pfet12mh_fc =  -1.3790e-03
+ dxld_pfet12mh_fc =   0.0000e+00
+ dsc1_pfet12mh_fc =   0.0000e+00
+ dvmax_pfet12mh_fc =  -1.3376e+04
+ dmueph1_pfet12mh_fc =   0.0000e+00
+ dxldld_pfet12mh_fc =   0.0000e+00
+ dtox_pfet12mh_fc =   0.0000e+00
+ dnsubc_pfet12mh_fc =   4.7613e+15
+ drd_pfet12mh_fc =   8.6275e-04
.endl fs_pfet12mh

.lib sf_pfet12mh
.param
+ dsc3_pfet12mh_fc =   0.0000e+00
+ dcj_pfet12mh_fc =   0.0000e+00
+ dcgso_pfet12mh_fc =   0.0000e+00
+ dvfbc_pfet12mh_fc =  -2.5743e-02
+ dcgdo_pfet12mh_fc =   0.0000e+00
+ dloverld_pfet12mh_fc =   0.0000e+00
+ dsc2_pfet12mh_fc =   1.3791e-03
+ dxld_pfet12mh_fc =   0.0000e+00
+ dsc1_pfet12mh_fc =   0.0000e+00
+ dvmax_pfet12mh_fc =   1.3378e+04
+ dmueph1_pfet12mh_fc =   0.0000e+00
+ dxldld_pfet12mh_fc =   0.0000e+00
+ dtox_pfet12mh_fc =   0.0000e+00
+ dnsubc_pfet12mh_fc =  -6.2495e+15
+ drd_pfet12mh_fc =  -7.8826e-04
.endl sf_pfet12mh

.lib fff_pfet12mh
.param
+ dsc3_pfet12mh_fc =   0.0000e+00
+ dcj_pfet12mh_fc =   0.0000e+00
+ dcgso_pfet12mh_fc =  -6.6667e-13
+ dvfbc_pfet12mh_fc =  -3.7332e-02
+ dcgdo_pfet12mh_fc =  -6.6667e-12
+ dloverld_pfet12mh_fc =   0.0000e+00
+ dsc2_pfet12mh_fc =   2.0000e-03
+ dxld_pfet12mh_fc =   0.0000e+00
+ dsc1_pfet12mh_fc =   0.0000e+00
+ dvmax_pfet12mh_fc =   1.9400e+04
+ dmueph1_pfet12mh_fc =   0.0000e+00
+ dxldld_pfet12mh_fc =   0.0000e+00
+ dtox_pfet12mh_fc =  -4.0000e-10
+ dnsubc_pfet12mh_fc =  -9.0629e+15
+ drd_pfet12mh_fc =  -1.1431e-03
.endl fff_pfet12mh

.lib ssf_pfet12mh
.param
+ dsc3_pfet12mh_fc =   0.0000e+00
+ dcj_pfet12mh_fc =   0.0000e+00
+ dcgso_pfet12mh_fc =   6.6667e-13
+ dvfbc_pfet12mh_fc =   4.6683e-02
+ dcgdo_pfet12mh_fc =   6.6667e-12
+ dloverld_pfet12mh_fc =   0.0000e+00
+ dsc2_pfet12mh_fc =  -2.0000e-03
+ dxld_pfet12mh_fc =   0.0000e+00
+ dsc1_pfet12mh_fc =   0.0000e+00
+ dvmax_pfet12mh_fc =  -1.9400e+04
+ dmueph1_pfet12mh_fc =   0.0000e+00
+ dxldld_pfet12mh_fc =   0.0000e+00
+ dtox_pfet12mh_fc =   4.0000e-10
+ dnsubc_pfet12mh_fc =   6.9055e+15
+ drd_pfet12mh_fc =   1.2513e-03
.endl ssf_pfet12mh


.lib tt_nfeti120m
.param
+ dsc3_nfeti120m_fc =   0.0000e+00
+ dcj_nfeti120m_fc =   0.0000e+00
+ dcgso_nfeti120m_fc =   0.0000e+00
+ dvfbc_nfeti120m_fc =   0.0000e+00
+ dcgdo_nfeti120m_fc =   0.0000e+00
+ dloverld_nfeti120m_fc =   0.0000e+00
+ dsc2_nfeti120m_fc =   0.0000e+00
+ dxld_nfeti120m_fc =   0.0000e+00
+ dsc1_nfeti120m_fc =   0.0000e+00
+ dvmax_nfeti120m_fc =   0.0000e+00
+ dmueph1_nfeti120m_fc =   0.0000e+00
+ dxldld_nfeti120m_fc =   0.0000e+00
+ dtox_nfeti120m_fc =   0.0000e+00
+ dnsubc_nfeti120m_fc =   0.0000e+00
+ drd_nfeti120m_fc =   0.0000e+00
.endl tt_nfeti120m

.lib ff_nfeti120m
.param
+ dsc3_nfeti120m_fc =   2.0000e-06
+ dcj_nfeti120m_fc =   0.0000e+00
+ dcgso_nfeti120m_fc =  -1.3333e-13
+ dvfbc_nfeti120m_fc =  -3.2320e-03
+ dcgdo_nfeti120m_fc =  -1.2000e-10
+ dloverld_nfeti120m_fc =   1.8872e-07
+ dsc2_nfeti120m_fc =   2.0000e-03
+ dxld_nfeti120m_fc =   0.0000e+00
+ dsc1_nfeti120m_fc =   2.4193e-02
+ dvmax_nfeti120m_fc =   0.0000e+00
+ dmueph1_nfeti120m_fc =   1.2000e+02
+ dxldld_nfeti120m_fc =   0.0000e+00
+ dtox_nfeti120m_fc =  -4.0000e-10
+ dnsubc_nfeti120m_fc =  -2.6552e+16
+ drd_nfeti120m_fc =  -1.8799e-03
.endl ff_nfeti120m

.lib ss_nfeti120m
.param
+ dsc3_nfeti120m_fc =  -2.0000e-06
+ dcj_nfeti120m_fc =   0.0000e+00
+ dcgso_nfeti120m_fc =   1.3333e-13
+ dvfbc_nfeti120m_fc =   8.6000e-03
+ dcgdo_nfeti120m_fc =   1.2000e-10
+ dloverld_nfeti120m_fc =  -2.1300e-07
+ dsc2_nfeti120m_fc =  -2.0000e-03
+ dxld_nfeti120m_fc =   0.0000e+00
+ dsc1_nfeti120m_fc =  -1.4453e-01
+ dvmax_nfeti120m_fc =   0.0000e+00
+ dmueph1_nfeti120m_fc =  -1.2552e+02
+ dxldld_nfeti120m_fc =   0.0000e+00
+ dtox_nfeti120m_fc =   4.0000e-10
+ dnsubc_nfeti120m_fc =   2.2608e+16
+ drd_nfeti120m_fc =   1.9064e-03
.endl ss_nfeti120m

.lib fs_nfeti120m
.param
+ dsc3_nfeti120m_fc =   1.3265e-06
+ dcj_nfeti120m_fc =   0.0000e+00
+ dcgso_nfeti120m_fc =   0.0000e+00
+ dvfbc_nfeti120m_fc =  -2.1437e-03
+ dcgdo_nfeti120m_fc =   0.0000e+00
+ dloverld_nfeti120m_fc =   1.2517e-07
+ dsc2_nfeti120m_fc =   1.3265e-03
+ dxld_nfeti120m_fc =   0.0000e+00
+ dsc1_nfeti120m_fc =   1.6047e-02
+ dvmax_nfeti120m_fc =   0.0000e+00
+ dmueph1_nfeti120m_fc =   7.9592e+01
+ dxldld_nfeti120m_fc =   0.0000e+00
+ dtox_nfeti120m_fc =   0.0000e+00
+ dnsubc_nfeti120m_fc =  -1.7611e+16
+ drd_nfeti120m_fc =  -1.2469e-03
.endl fs_nfeti120m

.lib sf_nfeti120m
.param
+ dsc3_nfeti120m_fc =  -1.3809e-06
+ dcj_nfeti120m_fc =   0.0000e+00
+ dcgso_nfeti120m_fc =   0.0000e+00
+ dvfbc_nfeti120m_fc =   5.9377e-03
+ dcgdo_nfeti120m_fc =   0.0000e+00
+ dloverld_nfeti120m_fc =  -1.4706e-07
+ dsc2_nfeti120m_fc =  -1.3809e-03
+ dxld_nfeti120m_fc =   0.0000e+00
+ dsc1_nfeti120m_fc =  -9.9790e-02
+ dvmax_nfeti120m_fc =   0.0000e+00
+ dmueph1_nfeti120m_fc =  -8.6663e+01
+ dxldld_nfeti120m_fc =   0.0000e+00
+ dtox_nfeti120m_fc =   0.0000e+00
+ dnsubc_nfeti120m_fc =   1.5609e+16
+ drd_nfeti120m_fc =   1.3162e-03
.endl sf_nfeti120m

.lib fff_nfeti120m
.param
+ dsc3_nfeti120m_fc =   2.0000e-06
+ dcj_nfeti120m_fc =   0.0000e+00
+ dcgso_nfeti120m_fc =  -1.3333e-13
+ dvfbc_nfeti120m_fc =  -3.2320e-03
+ dcgdo_nfeti120m_fc =  -1.2000e-10
+ dloverld_nfeti120m_fc =   1.8872e-07
+ dsc2_nfeti120m_fc =   2.0000e-03
+ dxld_nfeti120m_fc =   0.0000e+00
+ dsc1_nfeti120m_fc =   2.4193e-02
+ dvmax_nfeti120m_fc =   0.0000e+00
+ dmueph1_nfeti120m_fc =   1.2000e+02
+ dxldld_nfeti120m_fc =   0.0000e+00
+ dtox_nfeti120m_fc =  -4.0000e-10
+ dnsubc_nfeti120m_fc =  -2.6552e+16
+ drd_nfeti120m_fc =  -1.8799e-03
.endl fff_nfeti120m

.lib ssf_nfeti120m
.param
+ dsc3_nfeti120m_fc =  -2.0000e-06
+ dcj_nfeti120m_fc =   0.0000e+00
+ dcgso_nfeti120m_fc =   1.3333e-13
+ dvfbc_nfeti120m_fc =   8.6000e-03
+ dcgdo_nfeti120m_fc =   1.2000e-10
+ dloverld_nfeti120m_fc =  -2.1300e-07
+ dsc2_nfeti120m_fc =  -2.0000e-03
+ dxld_nfeti120m_fc =   0.0000e+00
+ dsc1_nfeti120m_fc =  -1.4453e-01
+ dvmax_nfeti120m_fc =   0.0000e+00
+ dmueph1_nfeti120m_fc =  -1.2552e+02
+ dxldld_nfeti120m_fc =   0.0000e+00
+ dtox_nfeti120m_fc =   4.0000e-10
+ dnsubc_nfeti120m_fc =   2.2608e+16
+ drd_nfeti120m_fc =   1.9064e-03
.endl ssf_nfeti120m

.lib tt_pfet120m
.param
+ dsc3_pfet120m_fc =   0.0000e+00
+ dcj_pfet120m_fc =   0.0000e+00
+ dcgso_pfet120m_fc =   0.0000e+00
+ dvfbc_pfet120m_fc =   0.0000e+00
+ dcgdo_pfet120m_fc =   0.0000e+00
+ dloverld_pfet120m_fc =   0.0000e+00
+ dsc2_pfet120m_fc =   0.0000e+00
+ dxld_pfet120m_fc =   0.0000e+00
+ dsc1_pfet120m_fc =   0.0000e+00
+ dvmax_pfet120m_fc =   0.0000e+00
+ dmueph1_pfet120m_fc =   0.0000e+00
+ dxldld_pfet120m_fc =   0.0000e+00
+ dtox_pfet120m_fc =   0.0000e+00
+ dnsubc_pfet120m_fc =   0.0000e+00
+ drd_pfet120m_fc =   0.0000e+00
.endl tt_pfet120m

.lib ff_pfet120m
.param
+ dsc3_pfet120m_fc =   0.0000e+00
+ dcj_pfet120m_fc =   0.0000e+00
+ dcgso_pfet120m_fc =  -1.3333e-11
+ dvfbc_pfet120m_fc =  -1.0470e-03
+ dcgdo_pfet120m_fc =  -2.0000e-10
+ dloverld_pfet120m_fc =   0.0000e+00
+ dsc2_pfet120m_fc =   0.0000e+00
+ dxld_pfet120m_fc =   0.0000e+00
+ dsc1_pfet120m_fc =   0.0000e+00
+ dvmax_pfet120m_fc =   8.2139e+05
+ dmueph1_pfet120m_fc =   4.6578e+01
+ dxldld_pfet120m_fc =   0.0000e+00
+ dtox_pfet120m_fc =  -4.0000e-10
+ dnsubc_pfet120m_fc =  -9.6262e+15
+ drd_pfet120m_fc =  -5.8431e-03
.endl ff_pfet120m

.lib ss_pfet120m
.param
+ dsc3_pfet120m_fc =   0.0000e+00
+ dcj_pfet120m_fc =   0.0000e+00
+ dcgso_pfet120m_fc =   1.3333e-11
+ dvfbc_pfet120m_fc =   9.6667e-03
+ dcgdo_pfet120m_fc =   2.0000e-10
+ dloverld_pfet120m_fc =   0.0000e+00
+ dsc2_pfet120m_fc =   0.0000e+00
+ dxld_pfet120m_fc =   0.0000e+00
+ dsc1_pfet120m_fc =   0.0000e+00
+ dvmax_pfet120m_fc =  -6.0016e+05
+ dmueph1_pfet120m_fc =  -4.6578e+01
+ dxldld_pfet120m_fc =   0.0000e+00
+ dtox_pfet120m_fc =   4.0000e-10
+ dnsubc_pfet120m_fc =   7.3397e+15
+ drd_pfet120m_fc =   5.5543e-03
.endl ss_pfet120m

.lib fs_pfet120m
.param
+ dsc3_pfet120m_fc =   0.0000e+00
+ dcj_pfet120m_fc =   0.0000e+00
+ dcgso_pfet120m_fc =   0.0000e+00
+ dvfbc_pfet120m_fc =   8.0226e-03
+ dcgdo_pfet120m_fc =   0.0000e+00
+ dloverld_pfet120m_fc =   0.0000e+00
+ dsc2_pfet120m_fc =   0.0000e+00
+ dxld_pfet120m_fc =   0.0000e+00
+ dsc1_pfet120m_fc =   0.0000e+00
+ dvmax_pfet120m_fc =  -4.9809e+05
+ dmueph1_pfet120m_fc =  -3.8656e+01
+ dxldld_pfet120m_fc =   0.0000e+00
+ dtox_pfet120m_fc =   0.0000e+00
+ dnsubc_pfet120m_fc =   6.0913e+15
+ drd_pfet120m_fc =   4.6096e-03
.endl fs_pfet120m

.lib sf_pfet120m
.param
+ dsc3_pfet120m_fc =   0.0000e+00
+ dcj_pfet120m_fc =   0.0000e+00
+ dcgso_pfet120m_fc =   0.0000e+00
+ dvfbc_pfet120m_fc =  -8.2866e-04
+ dcgdo_pfet120m_fc =   0.0000e+00
+ dloverld_pfet120m_fc =   0.0000e+00
+ dsc2_pfet120m_fc =   0.0000e+00
+ dxld_pfet120m_fc =   0.0000e+00
+ dsc1_pfet120m_fc =   0.0000e+00
+ dvmax_pfet120m_fc =   6.5010e+05
+ dmueph1_pfet120m_fc =   3.6865e+01
+ dxldld_pfet120m_fc =   0.0000e+00
+ dtox_pfet120m_fc =   0.0000e+00
+ dnsubc_pfet120m_fc =  -7.6188e+15
+ drd_pfet120m_fc =  -4.6246e-03
.endl sf_pfet120m

.lib fff_pfet120m
.param
+ dsc3_pfet120m_fc =   0.0000e+00
+ dcj_pfet120m_fc =   0.0000e+00
+ dcgso_pfet120m_fc =  -1.3333e-11
+ dvfbc_pfet120m_fc =  -1.0470e-03
+ dcgdo_pfet120m_fc =  -2.0000e-10
+ dloverld_pfet120m_fc =   0.0000e+00
+ dsc2_pfet120m_fc =   0.0000e+00
+ dxld_pfet120m_fc =   0.0000e+00
+ dsc1_pfet120m_fc =   0.0000e+00
+ dvmax_pfet120m_fc =   8.2139e+05
+ dmueph1_pfet120m_fc =   4.6578e+01
+ dxldld_pfet120m_fc =   0.0000e+00
+ dtox_pfet120m_fc =  -4.0000e-10
+ dnsubc_pfet120m_fc =  -9.6262e+15
+ drd_pfet120m_fc =  -5.8431e-03
.endl fff_pfet120m

.lib ssf_pfet120m
.param
+ dsc3_pfet120m_fc =   0.0000e+00
+ dcj_pfet120m_fc =   0.0000e+00
+ dcgso_pfet120m_fc =   1.3333e-11
+ dvfbc_pfet120m_fc =   9.6667e-03
+ dcgdo_pfet120m_fc =   2.0000e-10
+ dloverld_pfet120m_fc =   0.0000e+00
+ dsc2_pfet120m_fc =   0.0000e+00
+ dxld_pfet120m_fc =   0.0000e+00
+ dsc1_pfet120m_fc =   0.0000e+00
+ dvmax_pfet120m_fc =  -6.0016e+05
+ dmueph1_pfet120m_fc =  -4.6578e+01
+ dxldld_pfet120m_fc =   0.0000e+00
+ dtox_pfet120m_fc =   4.0000e-10
+ dnsubc_pfet120m_fc =   7.3397e+15
+ drd_pfet120m_fc =   5.5543e-03
.endl ssf_pfet120m

 
.lib hvrtt
.param
***********************************************************************
* "TT" corner : Nominal (default) process
***********************************************************************
+   fixcnrhvr   = 0
+ beta_hvnwr_fc = 0.0000e+00
+ wd_hvnwr_fc   = 0.0000e+00
+ cgsa_hvnwr_fc = 0.0000e+00
+ cgsp_hvnwr_fc = 0.0000e+00
+ cgda_hvnwr_fc = 0.0000e+00
+ cgdp_hvnwr_fc = 0.0000e+00
+ beta_hvpwr_fc = 0.0000e+00
+ wd_hvpwr_fc   = 0.0000e+00
+ cgsa_hvpwr_fc = 0.0000e+00
+ cgsp_hvpwr_fc = 0.0000e+00
+ cgda_hvpwr_fc = 0.0000e+00
+ cgdp_hvpwr_fc = 0.0000e+00
+ vta_pjfet_fc  = 0.0000e+00
+ cgsa_pjfet_fc = 0.0000e+00
+ cgsp_pjfet_fc = 0.0000e+00
+ cgda_pjfet_fc = 0.0000e+00
+ cgdp_pjfet_fc = 0.0000e+00
.endl hvrtt
 
.lib hvrmax
.param
***********************************************************************
* "RMAX" : High resistance
***********************************************************************
+   fixcnrhvr   = 1
+ beta_hvnwr_fc = -0.3472e-06
+ wd_hvnwr_fc   = 0.5000e-06
+ cgsa_hvnwr_fc = 0.8440e-05
+ cgsp_hvnwr_fc = 0.6040e-10
+ cgda_hvnwr_fc = 0.8440e-05
+ cgdp_hvnwr_fc = 0.6040e-10
+ beta_hvpwr_fc = -0.1704e-06
+ wd_hvpwr_fc   = 0.2500e-06
+ cgsa_hvpwr_fc = 0.8440e-05
+ cgsp_hvpwr_fc = 0.6040e-10
+ cgda_hvpwr_fc = 0.8440e-05
+ cgdp_hvpwr_fc = 0.6040e-10
+ vta_pjfet_fc  = -0.700e+00
+ cgsa_pjfet_fc = 0.1940e-04
+ cgsp_pjfet_fc = 0.8510e-10
+ cgda_pjfet_fc = 0.1940e-04
+ cgdp_pjfet_fc = 0.8510e-10
.endl hvrmax
 
.lib hvrmin
.param
***********************************************************************
* "RMIN" : Low resistance
***********************************************************************
+   fixcnrhvr   = 1
+ beta_hvnwr_fc = 0.5165e-06
+ wd_hvnwr_fc   = -0.500e-06
+ cgsa_hvnwr_fc = -0.844e-05
+ cgsp_hvnwr_fc = -0.604e-10
+ cgda_hvnwr_fc = -0.844e-05
+ cgdp_hvnwr_fc = -0.604e-10
+ beta_hvpwr_fc = 0.2129e-06
+ wd_hvpwr_fc   = -0.250e-06
+ cgsa_hvpwr_fc = -0.844e-05
+ cgsp_hvpwr_fc = -0.604e-10
+ cgda_hvpwr_fc = -0.844e-05
+ cgdp_hvpwr_fc = -0.604e-10
+ vta_pjfet_fc  = 0.8667e+00
+ cgsa_pjfet_fc = -0.195e-04
+ cgsp_pjfet_fc = -0.851e-10
+ cgda_pjfet_fc = -0.195e-04
+ cgdp_pjfet_fc = -0.851e-10
.endl hvrmin
 

.lib hvbiptt
.param
***********************************************************************
* "TT" corner : Nominal (default) process
***********************************************************************
+   fixcnrhvb   = 0
+ re_hvnpn_fc   = 0.0000e+00
+ rbi_hvnpn_fc  = 0.0000e+00
+ rbx_hvnpn_fc  = 0.0000e+00
+ rci_hvnpn_fc  = 0.0000e+00
+ rcx_hvnpn_fc  = 0.0000e+00
+ cje_hvnpn_fc  = 0.0000e+00
+ cjep_hvnpn_fc = 0.0000e+00
+ cjc_hvnpn_fc  = 0.0000e+00
+ cjcp_hvnpn_fc = 0.0000e+00
+ is_hvnpn_fc   = 0.0000e+00
+ ibei_hvnpn_fc = 0.0000e+00
+ iben_hvnpn_fc = 0.0000e+00
+ vef_hvnpn_fc  = 0.0000e+00
+ avc2_hvnpn_fc = 0.0000e+00
+ tf_hvnpn_fc   = 0.0000e+00
+ re_hvpnp_fc   = 0.0000e+00
+ rb_hvpnp_fc   = 0.0000e+00
+ rbm_hvpnp_fc  = 0.0000e+00
+ rc_hvpnp_fc   = 0.0000e+00
+ cje_hvpnp_fc  = 0.0000e+00
+ cjc_hvpnp_fc  = 0.0000e+00
+ is_hvpnp_fc   = 0.0000e+00
+ ikf_hvpnp_fc  = 0.0000e+00
+ bf_hvpnp_fc   = 0.0000e+00
+ vaf_hvpnp_fc  = 0.0000e+00
+ tf_hvpnp_fc   = 0.0000e+00
.endl hvbiptt
 
.lib hvbiphs
.param
***********************************************************************
* "BIPHS" : High Speed, High Beta
***********************************************************************
+   fixcnrhvb   = 1
+ re_hvnpn_fc   = -6.100e+00
+ rbi_hvnpn_fc  = -636.0e+00
+ rbx_hvnpn_fc  = -4.320e+00
+ rci_hvnpn_fc  = -110.8e+00
+ rcx_hvnpn_fc  = -4.480e+00
+ cje_hvnpn_fc  = -0.1322e-15
+ cjep_hvnpn_fc = -2.3800e-15
+ cjc_hvnpn_fc  = -0.2460e-15
+ cjcp_hvnpn_fc = -6.3400e-15
+ is_hvnpn_fc   = '2.825e-18-0.350e-18*p5vonly'
+ ibei_hvnpn_fc = '0.080e-19-0.250e-19*p5vonly'
+ iben_hvnpn_fc = 0.0000e+00
+ vef_hvnpn_fc  = '-5.08e+00-2.500e+00*p5vonly'
+ avc2_hvnpn_fc = '-0.60e+00+0.145e+00*p5vonly'
+ tf_hvnpn_fc   = -7.460e-12
+ re_hvpnp_fc   = -0.552e+00
+ rb_hvpnp_fc   = -8.410e+00
+ rbm_hvpnp_fc  = -0.804e+00
+ rc_hvpnp_fc   = -0.852e+00
+ cje_hvpnp_fc  = -16.80e-15
+ cjc_hvpnp_fc  = -18.60e-15
+ is_hvpnp_fc   = 2.250e-16
+ ikf_hvpnp_fc  = 0.700e-04
+ bf_hvpnp_fc   = 43.50e+00
+ vaf_hvpnp_fc  = -41.00e+00
+ tf_hvpnp_fc   = -0.264e-09
.endl hvbiphs
 
.lib hvbiplb
.param
***********************************************************************
* "BIPLB" : Low Speed, Low Beta
***********************************************************************
+   fixcnrhvb   = 1
+ re_hvnpn_fc   = 6.100e+00
+ rbi_hvnpn_fc  = 636.0e+00
+ rbx_hvnpn_fc  = 4.320e+00
+ rci_hvnpn_fc  = 110.8e+00
+ rcx_hvnpn_fc  = 4.480e+00
+ cje_hvnpn_fc  = 0.1322e-15
+ cjep_hvnpn_fc = 2.3800e-15
+ cjc_hvnpn_fc  = 0.2460e-15
+ cjcp_hvnpn_fc = 6.3400e-15
+ is_hvnpn_fc   = '-1.975e-18+0.30e-18*p5vonly'
+ ibei_hvnpn_fc = '0.155e-19+0.90e-19*p5vonly'
+ iben_hvnpn_fc = 0.0000e+00
+ vef_hvnpn_fc  = '5.08e+00+2.500e+00*p5vonly'
+ avc2_hvnpn_fc = '0.0e+00-0.505e+00*p5vonly'
+ tf_hvnpn_fc   = 7.460e-12
+ re_hvpnp_fc   = 0.552e+00
+ rb_hvpnp_fc   = 8.410e+00
+ rbm_hvpnp_fc  = 0.804e+00
+ rc_hvpnp_fc   = 0.852e+00
+ cje_hvpnp_fc  = 16.80e-15
+ cjc_hvpnp_fc  = 18.60e-15
+ is_hvpnp_fc   = -2.250e-16
+ ikf_hvpnp_fc  = -0.700e-04
+ bf_hvpnp_fc   = -43.50e+00
+ vaf_hvpnp_fc  = 41.00e+00
+ tf_hvpnp_fc   = 0.264e-09
.endl hvbiplb
 

.lib hvtt
.param
***********************************************************************
* "TT" corner : Nominal (default) process
***********************************************************************
+  fixcnrhv = 0
+  cor_hv_diode = 0
.lib 'fixed_corner_hv.inc' tt_nfeti20t
.lib 'fixed_corner_hv.inc' tt_pfet20t
.lib 'fixed_corner_hv.inc' tt_nfeti50t
.lib 'fixed_corner_hv.inc' tt_pfet50t
.lib 'fixed_corner_hv.inc' tt_nfet20mh
.lib 'fixed_corner_hv.inc' tt_nfeti25m
.lib 'fixed_corner_hv.inc' tt_pfet25m
.lib 'fixed_corner_hv.inc' tt_nfeti50m
.lib 'fixed_corner_hv.inc' tt_pfet50m
.lib 'fixed_corner_hv.inc' tt_nfeti20h
.lib 'fixed_corner_hv.inc' tt_pfet20h
.lib 'fixed_corner_hv.inc' tt_nfet20hs
.lib 'fixed_corner_hv.inc' tt_pfet20hs
.lib 'fixed_corner_hv.inc' tt_nfeti50h
.lib 'fixed_corner_hv.inc' tt_pfet50h
.lib 'fixed_corner_hv.inc' tt_nfet50hs
.lib 'fixed_corner_hv.inc' tt_pfet50hs
.lib 'fixed_corner_hv.inc' tt_nfet12mh
.lib 'fixed_corner_hv.inc' tt_pfet12mh
.lib 'fixed_corner_hv.inc' tt_nfeti120m
.lib 'fixed_corner_hv.inc' tt_pfet120m
.endl hvtt

.lib hvff
.param
***********************************************************************
* "FF" corner : "Fast" NMOS, "Fast" PMOS
***********************************************************************
+  fixcnrhv = 1
+  cor_hv_diode = +3.0
.lib 'fixed_corner_hv.inc' ff_nfeti20t
.lib 'fixed_corner_hv.inc' ff_pfet20t
.lib 'fixed_corner_hv.inc' ff_nfeti50t
.lib 'fixed_corner_hv.inc' ff_pfet50t
.lib 'fixed_corner_hv.inc' ff_nfet20mh
.lib 'fixed_corner_hv.inc' ff_nfeti25m
.lib 'fixed_corner_hv.inc' ff_pfet25m
.lib 'fixed_corner_hv.inc' ff_nfeti50m
.lib 'fixed_corner_hv.inc' ff_pfet50m
.lib 'fixed_corner_hv.inc' ff_nfeti20h
.lib 'fixed_corner_hv.inc' ff_pfet20h
.lib 'fixed_corner_hv.inc' ff_nfet20hs
.lib 'fixed_corner_hv.inc' ff_pfet20hs
.lib 'fixed_corner_hv.inc' ff_nfeti50h
.lib 'fixed_corner_hv.inc' ff_pfet50h
.lib 'fixed_corner_hv.inc' ff_nfet50hs
.lib 'fixed_corner_hv.inc' ff_pfet50hs
.lib 'fixed_corner_hv.inc' ff_nfet12mh
.lib 'fixed_corner_hv.inc' ff_pfet12mh
.lib 'fixed_corner_hv.inc' ff_nfeti120m
.lib 'fixed_corner_hv.inc' ff_pfet120m
.endl hvff

.lib hvss
.param
***********************************************************************
* "SS" corner : "Slow" NMOS, "Slow" PMOS
***********************************************************************
+  fixcnrhv = 1
+  cor_hv_diode = -3.0
.lib 'fixed_corner_hv.inc' ss_nfeti20t
.lib 'fixed_corner_hv.inc' ss_pfet20t
.lib 'fixed_corner_hv.inc' ss_nfeti50t
.lib 'fixed_corner_hv.inc' ss_pfet50t
.lib 'fixed_corner_hv.inc' ss_nfet20mh
.lib 'fixed_corner_hv.inc' ss_nfeti25m
.lib 'fixed_corner_hv.inc' ss_pfet25m
.lib 'fixed_corner_hv.inc' ss_nfeti50m
.lib 'fixed_corner_hv.inc' ss_pfet50m
.lib 'fixed_corner_hv.inc' ss_nfeti20h
.lib 'fixed_corner_hv.inc' ss_pfet20h
.lib 'fixed_corner_hv.inc' ss_nfet20hs
.lib 'fixed_corner_hv.inc' ss_pfet20hs
.lib 'fixed_corner_hv.inc' ss_nfeti50h
.lib 'fixed_corner_hv.inc' ss_pfet50h
.lib 'fixed_corner_hv.inc' ss_nfet50hs
.lib 'fixed_corner_hv.inc' ss_pfet50hs
.lib 'fixed_corner_hv.inc' ss_nfet12mh
.lib 'fixed_corner_hv.inc' ss_pfet12mh
.lib 'fixed_corner_hv.inc' ss_nfeti120m
.lib 'fixed_corner_hv.inc' ss_pfet120m
.endl hvss

.lib hvfs
.param
***********************************************************************
* "FS" corner : "Fast" NMOS, "Slow" PMOS
***********************************************************************
+  fixcnrhv = 1
+  cor_hv_diode = 0
.lib 'fixed_corner_hv.inc' fs_nfeti20t
.lib 'fixed_corner_hv.inc' fs_pfet20t
.lib 'fixed_corner_hv.inc' fs_nfeti50t
.lib 'fixed_corner_hv.inc' fs_pfet50t
.lib 'fixed_corner_hv.inc' fs_nfet20mh
.lib 'fixed_corner_hv.inc' fs_nfeti25m
.lib 'fixed_corner_hv.inc' fs_pfet25m
.lib 'fixed_corner_hv.inc' fs_nfeti50m
.lib 'fixed_corner_hv.inc' fs_pfet50m
.lib 'fixed_corner_hv.inc' fs_nfeti20h
.lib 'fixed_corner_hv.inc' fs_pfet20h
.lib 'fixed_corner_hv.inc' fs_nfet20hs
.lib 'fixed_corner_hv.inc' fs_pfet20hs
.lib 'fixed_corner_hv.inc' fs_nfeti50h
.lib 'fixed_corner_hv.inc' fs_pfet50h
.lib 'fixed_corner_hv.inc' fs_nfet50hs
.lib 'fixed_corner_hv.inc' fs_pfet50hs
.lib 'fixed_corner_hv.inc' fs_nfet12mh
.lib 'fixed_corner_hv.inc' fs_pfet12mh
.lib 'fixed_corner_hv.inc' fs_nfeti120m
.lib 'fixed_corner_hv.inc' fs_pfet120m
.endl hvfs

.lib hvsf
.param
***********************************************************************
* "SF" corner : "Slow" NMOS, "Fast" PMOS
***********************************************************************
+  fixcnrhv = 1
+  cor_hv_diode = 0
.lib 'fixed_corner_hv.inc' sf_nfeti20t
.lib 'fixed_corner_hv.inc' sf_pfet20t
.lib 'fixed_corner_hv.inc' sf_nfeti50t
.lib 'fixed_corner_hv.inc' sf_pfet50t
.lib 'fixed_corner_hv.inc' sf_nfet20mh
.lib 'fixed_corner_hv.inc' sf_nfeti25m
.lib 'fixed_corner_hv.inc' sf_pfet25m
.lib 'fixed_corner_hv.inc' sf_nfeti50m
.lib 'fixed_corner_hv.inc' sf_pfet50m
.lib 'fixed_corner_hv.inc' sf_nfeti20h
.lib 'fixed_corner_hv.inc' sf_pfet20h
.lib 'fixed_corner_hv.inc' sf_nfet20hs
.lib 'fixed_corner_hv.inc' sf_pfet20hs
.lib 'fixed_corner_hv.inc' sf_nfeti50h
.lib 'fixed_corner_hv.inc' sf_pfet50h
.lib 'fixed_corner_hv.inc' sf_nfet50hs
.lib 'fixed_corner_hv.inc' sf_pfet50hs
.lib 'fixed_corner_hv.inc' sf_nfet12mh
.lib 'fixed_corner_hv.inc' sf_pfet12mh
.lib 'fixed_corner_hv.inc' sf_nfeti120m
.lib 'fixed_corner_hv.inc' sf_pfet120m
.endl hvsf

.lib hvfff
.param
***********************************************************************
* "FFF" functional corner : "Fast" NMOS, "Fast" PMOS
***********************************************************************
+  fixcnrhv = 1
+  cor_hv_diode = +3.0
.lib 'fixed_corner_hv.inc' fff_nfeti20t
.lib 'fixed_corner_hv.inc' fff_pfet20t
.lib 'fixed_corner_hv.inc' fff_nfeti50t
.lib 'fixed_corner_hv.inc' fff_pfet50t
.lib 'fixed_corner_hv.inc' fff_nfet20mh
.lib 'fixed_corner_hv.inc' fff_nfeti25m
.lib 'fixed_corner_hv.inc' fff_pfet25m
.lib 'fixed_corner_hv.inc' fff_nfeti50m
.lib 'fixed_corner_hv.inc' fff_pfet50m
.lib 'fixed_corner_hv.inc' fff_nfeti20h
.lib 'fixed_corner_hv.inc' fff_pfet20h
.lib 'fixed_corner_hv.inc' fff_nfet20hs
.lib 'fixed_corner_hv.inc' fff_pfet20hs
.lib 'fixed_corner_hv.inc' fff_nfeti50h
.lib 'fixed_corner_hv.inc' fff_pfet50h
.lib 'fixed_corner_hv.inc' fff_nfet50hs
.lib 'fixed_corner_hv.inc' fff_pfet50hs
.lib 'fixed_corner_hv.inc' fff_nfet12mh
.lib 'fixed_corner_hv.inc' fff_pfet12mh
.lib 'fixed_corner_hv.inc' fff_nfeti120m
.lib 'fixed_corner_hv.inc' fff_pfet120m
.endl hvfff

.lib hvssf
.param
***********************************************************************
* "SSF" functional corner : "Slow" NMOS, "Slow" PMOS
***********************************************************************
+  fixcnrhv = 1
+  cor_hv_diode = -3.0
.lib 'fixed_corner_hv.inc' ssf_nfeti20t
.lib 'fixed_corner_hv.inc' ssf_pfet20t
.lib 'fixed_corner_hv.inc' ssf_nfeti50t
.lib 'fixed_corner_hv.inc' ssf_pfet50t
.lib 'fixed_corner_hv.inc' ssf_nfet20mh
.lib 'fixed_corner_hv.inc' ssf_nfeti25m
.lib 'fixed_corner_hv.inc' ssf_pfet25m
.lib 'fixed_corner_hv.inc' ssf_nfeti50m
.lib 'fixed_corner_hv.inc' ssf_pfet50m
.lib 'fixed_corner_hv.inc' ssf_nfeti20h
.lib 'fixed_corner_hv.inc' ssf_pfet20h
.lib 'fixed_corner_hv.inc' ssf_nfet20hs
.lib 'fixed_corner_hv.inc' ssf_pfet20hs
.lib 'fixed_corner_hv.inc' ssf_nfeti50h
.lib 'fixed_corner_hv.inc' ssf_pfet50h
.lib 'fixed_corner_hv.inc' ssf_nfet50hs
.lib 'fixed_corner_hv.inc' ssf_pfet50hs
.lib 'fixed_corner_hv.inc' ssf_nfet12mh
.lib 'fixed_corner_hv.inc' ssf_pfet12mh
.lib 'fixed_corner_hv.inc' ssf_nfeti120m
.lib 'fixed_corner_hv.inc' ssf_pfet120m
.endl hvssf
